const data = [
  { name: "Paddie Farlane", language: "Chinese", company: "Aibox", departure: "Training" },
  { name: "Gwyneth Ridoutt", language: "Pali", company: "Brainlounge", departure: "Research and Development" },
  { name: "Noella Gherardini", language: "Kanuri", company: "Jaloo", departure: "Research and Development" },
  { name: "Sherry Brennen", language: "Limburgan", company: "Skinix", departure: "Engineering" },
  { name: "Trista Reah", language: "Romansh", company: "Edgetag", departure: "Services" },
  { name: "Judas Groombridge", language: "Chichewa", company: "Flashspan", departure: "Marketing" },
  { name: "Bartholomeus Tenwick", language: "Bengali", company: "Voolia", departure: "Product Management" },
  { name: "Sloane Armit", language: "Spanish", company: "Edgeblab", departure: "Legal" },
  { name: "Tiffani Kings", language: "Venda", company: "Skyba", departure: "Marketing" },
  { name: "Reuben Fretwell", language: "Latvian", company: "Tagchat", departure: "Accounting" },
  { name: "Jedediah Riping", language: "Samoan", company: "Topicshots", departure: "Accounting" },
  { name: "Leoline Posen", language: "Yoruba", company: "Quimm", departure: "Product Management" },
  { name: "Larry Mapson", language: "Navajo", company: "Feedmix", departure: "Legal" },
  { name: "Laure Dugmore", language: "Spanish", company: "Gabtune", departure: "Product Management" },
  { name: "Winna Tasseler", language: "Indonesian", company: "Tagtune", departure: "Business Development" },
  { name: "Glen Vallens", language: "Kinyarwanda", company: "Feedfire", departure: "Research and Development" },
  { name: "Flore Issacoff", language: "Wolof", company: "DabZ", departure: "Marketing" },
  { name: "Gretna Keinrat", language: "Lingala", company: "Kamba", departure: "Marketing" },
  { name: "Teena Stetlye", language: "Tajik", company: "Jabbersphere", departure: "Engineering" },
  { name: "Ilka Bridgewood", language: "Oromo", company: "Roodel", departure: "Training" },
  { name: "Tomlin Al Hirsi", language: "Avestan", company: "Midel", departure: "Research and Development" },
  { name: "Rebekkah Bignold", language: "Swahili", company: "Topicware", departure: "Engineering" },
  { name: "Marrissa Chandlar", language: "Navajo", company: "Cogilith", departure: "Support" },
  { name: "Prue Rowatt", language: "Ndebele, North", company: "Quire", departure: "Product Management" },
  { name: "Colene Robke", language: "Kannada", company: "Zooxo", departure: "Business Development" },
  { name: "Jody Stivers", language: "Kashmiri", company: "Wordify", departure: "Engineering" },
  { name: "Georgine Doget", language: "Czech", company: "Lazzy", departure: "Human Resources" },
  { name: "George Wilbud", language: "Ido", company: "Jetwire", departure: "Services" },
  { name: "Marcelia Clatworthy", language: "Bislama", company: "Trunyx", departure: "Support" },
  { name: "Jamie Minithorpe", language: "Aymara", company: "Reallinks", departure: "Engineering" },
  { name: "Winthrop Triggs", language: "Sardinian", company: "Viva", departure: "Support" },
  { name: "Jacquelin Cosgrave", language: "Uighur", company: "Realblab", departure: "Product Management" },
  { name: "Robbie Shawell", language: "Hiri Motu", company: "Trilia", departure: "Product Management" },
  { name: "Georgette Reasce", language: "Bokmål, Norwegian", company: "Latz", departure: "Support" },
  { name: "Aldrich Mozzetti", language: "Interlingua (International Auxiliary Language Association)", company: "Topiclounge", departure: "Accounting" },
  { name: "Bartholemy Sighard", language: "Slovak", company: "Brightdog", departure: "Services" },
  { name: "Ezmeralda Giorgeschi", language: "Danish", company: "Topicware", departure: "Business Development" },
  { name: "Dwayne Tichner", language: "Malayalam", company: "Blogtag", departure: "Research and Development" },
  { name: "Shayla Wibberley", language: "Corsican", company: "Chatterbridge", departure: "Research and Development" },
  { name: "Templeton Lodemann", language: "Basque", company: "LiveZ", departure: "Research and Development" },
  { name: "Marcel Fitzjohn", language: "Gaelic", company: "Kwideo", departure: "Human Resources" },
  { name: "Geoff Winspare", language: "Irish", company: "Yombu", departure: "Accounting" },
  { name: "Marge Benditt", language: "English", company: "Miboo", departure: "Human Resources" },
  { name: "Meggie Yanshinov", language: "Russian", company: "Yotz", departure: "Services" },
  { name: "Inesita Blazdell", language: "Oriya", company: "Oyoba", departure: "Sales" },
  { name: "Sadie Boundy", language: "Faroese", company: "Brainsphere", departure: "Business Development" },
  { name: "Bartie Holby", language: "Ossetian", company: "Browseblab", departure: "Services" },
  { name: "Viole Semrad", language: "Javanese", company: "Realfire", departure: "Marketing" },
  { name: "Niki Yanez", language: "Tagalog", company: "Divavu", departure: "Human Resources" },
  { name: "Rolland Enoksson", language: "Czech", company: "Bluejam", departure: "Accounting" },
  { name: "Cecil Yell", language: "Luxembourgish", company: "Kwideo", departure: "Sales" },
  { name: "Julie Kloisner", language: "Oriya", company: "Oyoba", departure: "Accounting" },
  { name: "Cookie Gillice", language: "Abkhazian", company: "Tagopia", departure: "Product Management" },
  { name: "Neilla Blease", language: "Sanskrit", company: "Vitz", departure: "Sales" },
  { name: "Judd Marcroft", language: "Albanian", company: "Lazzy", departure: "Support" },
  { name: "Gertrud Rayworth", language: "Interlingue", company: "Skiba", departure: "Accounting" },
  { name: "Mirabella Trusler", language: "Haitian", company: "Topicblab", departure: "Product Management" },
  { name: "Terrijo Rembrant", language: "Afar", company: "Oyoba", departure: "Human Resources" },
  { name: "Kelly Losseljong", language: "Bengali", company: "Eadel", departure: "Marketing" },
  { name: "Fran Farragher", language: "Fulah", company: "Linktype", departure: "Research and Development" },
  { name: "Hirsch Comiam", language: "Rundi", company: "Feedspan", departure: "Sales" },
  { name: "Marni Ride", language: "Kuanyama", company: "Roomm", departure: "Support" },
  { name: "Simon Van Dalen", language: "Rundi", company: "Dabtype", departure: "Human Resources" },
  { name: "Kinna Juniper", language: "Catalan", company: "Skinix", departure: "Product Management" },
  { name: "Tiphani Waleran", language: "Sindhi", company: "Zoombox", departure: "Product Management" },
  { name: "Hazel Rosenthal", language: "Breton", company: "Thoughtstorm", departure: "Legal" },
  { name: "Gage Kibble", language: "Aragonese", company: "Roombo", departure: "Human Resources" },
  { name: "Salomi Foster", language: "Hiri Motu", company: "Rhyzio", departure: "Training" },
  { name: "Hoebart Tumility", language: "Vietnamese", company: "Linklinks", departure: "Services" },
  { name: "Vinnie Spandley", language: "Ndebele, North", company: "DabZ", departure: "Business Development" },
  { name: "Carlene O'Cridigan", language: "Kannada", company: "Pixope", departure: "Human Resources" },
  { name: "Billie Gliddon", language: "Corsican", company: "Divape", departure: "Product Management" },
  { name: "Jasun Joslyn", language: "Kazakh", company: "Trilith", departure: "Sales" },
  { name: "Crosby Ianni", language: "Turkish", company: "InnoZ", departure: "Sales" },
  { name: "Brooke McQuaker", language: "Bashkir", company: "Zoomlounge", departure: "Research and Development" },
  { name: "Killy Marcu", language: "Lingala", company: "Dabfeed", departure: "Accounting" },
  { name: "Erina Domino", language: "Arabic", company: "Skilith", departure: "Support" },
  { name: "Zacharias Raddon", language: "Norwegian Nynorsk", company: "InnoZ", departure: "Research and Development" },
  { name: "Welsh Woolam", language: "Pushto", company: "InnoZ", departure: "Training" },
  { name: "Inger Shama", language: "Xhosa", company: "Dynazzy", departure: "Services" },
  { name: "Gabbie Blaase", language: "Macedonian", company: "Youfeed", departure: "Services" },
  { name: "Massimiliano Demchen", language: "Maori", company: "Gigabox", departure: "Training" },
  { name: "Jaimie Van Salzberger", language: "Ndebele, South", company: "Trupe", departure: "Engineering" },
  { name: "Maure Sollis", language: "Georgian", company: "Twinte", departure: "Research and Development" },
  { name: "Leonelle Masson", language: "Slovenian", company: "Demivee", departure: "Engineering" },
  { name: "Kiah Geleman", language: "Dutch", company: "Digitube", departure: "Product Management" },
  { name: "Darlene Dakhov", language: "Kinyarwanda", company: "Voonix", departure: "Sales" },
  { name: "Ody Dibben", language: "Dzongkha", company: "Tazz", departure: "Legal" },
  { name: "Dewitt Schultze", language: "Tagalog", company: "Quatz", departure: "Human Resources" },
  { name: "Willey Mouget", language: "Yoruba", company: "Quaxo", departure: "Accounting" },
  { name: "Adelice Krzyzanowski", language: "Sardinian", company: "Devbug", departure: "Product Management" },
  { name: "Morganne Puttock", language: "Burmese", company: "Blogpad", departure: "Training" },
  { name: "Agnola Catmull", language: "Kashmiri", company: "Skyble", departure: "Services" },
  { name: "Guglielma Covet", language: "Nepali", company: "Yakijo", departure: "Services" },
  { name: "Bobbette Hartell", language: "Portuguese", company: "Zooxo", departure: "Engineering" },
  { name: "Lindsy Ivens", language: "Quechua", company: "Minyx", departure: "Human Resources" },
  { name: "Isaac Diviny", language: "Tsonga", company: "Zoombeat", departure: "Support" },
  { name: "Lizabeth Malster", language: "Inuktitut", company: "Tagopia", departure: "Research and Development" },
  { name: "Bucky Strawbridge", language: "Polish", company: "Quatz", departure: "Marketing" },
  { name: "Tamara Sabathier", language: "Ido", company: "Tanoodle", departure: "Services" },
  { name: "Gertruda Virr", language: "French", company: "Livepath", departure: "Support" },
  { name: "Travers Hamlett", language: "Vietnamese", company: "Abatz", departure: "Services" },
  { name: "Etienne Tasch", language: "Tswana", company: "Gigaclub", departure: "Product Management" },
  { name: "Bernete Morot", language: "Persian", company: "Gabcube", departure: "Services" },
  { name: "Ermina Tomaskov", language: "Latin", company: "Dynazzy", departure: "Support" },
  { name: "Constancia Sherrard", language: "Russian", company: "Oozz", departure: "Product Management" },
  { name: "Karee Onians", language: "Hebrew", company: "Skipstorm", departure: "Engineering" },
  { name: "Hilda Vowell", language: "Abkhazian", company: "Browseblab", departure: "Services" },
  { name: "Verina Douche", language: "Italian", company: "Feedmix", departure: "Training" },
  { name: "Angelita Shard", language: "Zhuang", company: "Innojam", departure: "Product Management" },
  { name: "Foster Riddler", language: "Breton", company: "Skiba", departure: "Business Development" },
  { name: "Casper Golly", language: "Russian", company: "Fivebridge", departure: "Product Management" },
  { name: "Shel Wandrey", language: "Sango", company: "Mita", departure: "Research and Development" },
  { name: "Sidonia Ferrer", language: "Javanese", company: "Pixoboo", departure: "Accounting" },
  { name: "Elaine Elder", language: "Sotho, Southern", company: "Oyonder", departure: "Human Resources" },
  { name: "Barthel Surgeon", language: "Hausa", company: "Yodo", departure: "Support" },
  { name: "Clarabelle Brower", language: "Sardinian", company: "Centidel", departure: "Research and Development" },
  { name: "Tamar Cisson", language: "Dzongkha", company: "Tagfeed", departure: "Research and Development" },
  { name: "Evangelin Edsall", language: "Hausa", company: "Edgeclub", departure: "Services" },
  { name: "Angelique Neil", language: "Urdu", company: "Voomm", departure: "Legal" },
  { name: "Felice Elven", language: "Tonga (Tonga Islands)", company: "Aivee", departure: "Legal" },
  { name: "Malanie Jowitt", language: "Rundi", company: "Lazzy", departure: "Legal" },
  { name: "Consuela Bradforth", language: "Kanuri", company: "Edgeify", departure: "Human Resources" },
  { name: "Tomasine Willock", language: "Latin", company: "Feedfish", departure: "Product Management" },
  { name: "Denney Itschakov", language: "German", company: "Podcat", departure: "Sales" },
  { name: "Jamesy Cockings", language: "Northern Sami", company: "Photobug", departure: "Services" },
  { name: "Howie Hudspith", language: "Croatian", company: "Bluejam", departure: "Human Resources" },
  { name: "Tandie Folan", language: "Afar", company: "Kwinu", departure: "Human Resources" },
  { name: "Kimble Mattke", language: "Spanish", company: "Yoveo", departure: "Business Development" },
  { name: "Jennette Kyberd", language: "Manx", company: "Ooba", departure: "Human Resources" },
  { name: "Abba Teacy", language: "Kuanyama", company: "Skilith", departure: "Human Resources" },
  { name: "Piper Manzell", language: "Kurdish", company: "Edgeclub", departure: "Training" },
  { name: "Rooney Bolus", language: "Avestan", company: "Wikido", departure: "Support" },
  { name: "Tina Jackling", language: "Sotho, Southern", company: "Skimia", departure: "Product Management" },
  { name: "Cyndy Larrie", language: "Gujarati", company: "Skyndu", departure: "Business Development" },
  { name: "Elka Twelvetree", language: "Tigrinya", company: "Twitterworks", departure: "Engineering" },
  { name: "Anastasie O'Mailey", language: "Irish", company: "Feedmix", departure: "Marketing" },
  { name: "Egon Norcott", language: "Bambara", company: "Zoomdog", departure: "Training" },
  { name: "Shoshanna McGibbon", language: "Walloon", company: "Twimbo", departure: "Services" },
  { name: "Fedora Nurny", language: "Twi", company: "Realpoint", departure: "Product Management" },
  { name: "Adolphe Ingarfill", language: "Occitan (post 1500)", company: "Centidel", departure: "Support" },
  { name: "Marti Amthor", language: "Somali", company: "Devify", departure: "Legal" },
  { name: "Penny Espin", language: "Ido", company: "Leenti", departure: "Training" },
  { name: "Patten Normabell", language: "Luxembourgish", company: "Brainverse", departure: "Legal" },
  { name: "Bettine Thormwell", language: "Somali", company: "Jabbersphere", departure: "Sales" },
  { name: "Malorie Larcier", language: "Korean", company: "Skaboo", departure: "Human Resources" },
  { name: "Theo Kaser", language: "Kashmiri", company: "Gigaclub", departure: "Marketing" },
  { name: "Haven Cowlin", language: "Georgian", company: "Jamia", departure: "Services" },
  { name: "Ingunna Drover", language: "Afrikaans", company: "Jabbersphere", departure: "Product Management" },
  { name: "Millie Dilks", language: "Bashkir", company: "DabZ", departure: "Research and Development" },
  { name: "Barbra Sambles", language: "Bokmål, Norwegian", company: "BlogXS", departure: "Sales" },
  { name: "Correy Buntine", language: "Dzongkha", company: "Fivespan", departure: "Sales" },
  { name: "Cortney Sea", language: "Sotho, Southern", company: "Dazzlesphere", departure: "Legal" },
  { name: "Oren Petkovic", language: "Croatian", company: "Buzzbean", departure: "Marketing" },
  { name: "Cody Drewry", language: "Afar", company: "Topicstorm", departure: "Training" },
  { name: "Florry Grishelyov", language: "Amharic", company: "Feedfire", departure: "Legal" },
  { name: "Joshuah Gabbat", language: "Sotho, Southern", company: "Shufflebeat", departure: "Services" },
  { name: "Carlynne Hutson", language: "Manx", company: "Zoomdog", departure: "Marketing" },
  { name: "Hollie Fraschini", language: "Tigrinya", company: "Fliptune", departure: "Legal" },
  { name: "Katerine Scrowton", language: "Abkhazian", company: "Zoonder", departure: "Legal" },
  { name: "Lezlie Yakuntsov", language: "Armenian", company: "Twinte", departure: "Training" },
  { name: "Anatol Toynbee", language: "Faroese", company: "Eadel", departure: "Services" },
  { name: "Wilie McDowall", language: "Ndebele, North", company: "Jabberstorm", departure: "Accounting" },
  { name: "Bernita McGeffen", language: "Uzbek", company: "Thoughtstorm", departure: "Business Development" },
  { name: "Eugen Blazej", language: "Marshallese", company: "Jatri", departure: "Services" },
  { name: "Mella Couroy", language: "Maltese", company: "Skalith", departure: "Research and Development" },
  { name: "Jacques Summerlie", language: "Kazakh", company: "Skynoodle", departure: "Product Management" },
  { name: "Truman Chafer", language: "Sanskrit", company: "Quatz", departure: "Business Development" },
  { name: "Natale Ible", language: "Danish", company: "Kwimbee", departure: "Accounting" },
  { name: "Birgit Bangle", language: "Bislama", company: "Topicstorm", departure: "Human Resources" },
  { name: "Elsi Iliffe", language: "Ossetian", company: "Izio", departure: "Human Resources" },
  { name: "Dayle Martinho", language: "Uighur", company: "Oyoba", departure: "Accounting" },
  { name: "Hayley Allebone", language: "Lingala", company: "Leexo", departure: "Sales" },
  { name: "Ave Yurasov", language: "Latvian", company: "Twitterbridge", departure: "Marketing" },
  { name: "Marcellus Peel", language: "Norwegian", company: "Demimbu", departure: "Services" },
  { name: "Teodorico Canto", language: "French", company: "Devify", departure: "Legal" },
  { name: "Virginie McGray", language: "Fulah", company: "Oyope", departure: "Support" },
  { name: "Morley Pepineaux", language: "Herero", company: "Mudo", departure: "Support" },
  { name: "Sharona Renault", language: "Albanian", company: "Podcat", departure: "Legal" },
  { name: "Baudoin Caine", language: "Dzongkha", company: "Topicstorm", departure: "Services" },
  { name: "Emmery Chilley", language: "Javanese", company: "Browsedrive", departure: "Human Resources" },
  { name: "Rheba Tabram", language: "Croatian", company: "Bubblemix", departure: "Training" },
  { name: "Odessa Squier", language: "Tatar", company: "Thoughtsphere", departure: "Engineering" },
  { name: "Care Gergus", language: "Akan", company: "Kwideo", departure: "Sales" },
  { name: "Jamie Balsdone", language: "Zhuang", company: "Feedfire", departure: "Accounting" },
  { name: "Carolyn Yandell", language: "Avestan", company: "Quinu", departure: "Services" },
  { name: "Jaimie Clark", language: "Norwegian Nynorsk", company: "Miboo", departure: "Research and Development" },
  { name: "Reinhold Parram", language: "Inupiaq", company: "Vidoo", departure: "Legal" },
  { name: "Jacintha Daintith", language: "Macedonian", company: "Yabox", departure: "Marketing" },
  { name: "Ethel Griffin", language: "Interlingue", company: "Meevee", departure: "Marketing" },
  { name: "Bevvy Cauley", language: "Sardinian", company: "Jaxbean", departure: "Human Resources" },
  { name: "Obie Ennor", language: "Luxembourgish", company: "Livetube", departure: "Business Development" },
  { name: "Petrina Cancellor", language: "Kikuyu", company: "Midel", departure: "Marketing" },
  { name: "Annadiane Giacomini", language: "Russian", company: "Flashset", departure: "Engineering" },
  { name: "Garwin Fehely", language: "Chechen", company: "Devcast", departure: "Human Resources" },
  { name: "Halette Conboy", language: "Serbian", company: "Topicware", departure: "Engineering" },
  { name: "Serena Bartlomiej", language: "Catalan", company: "Voonix", departure: "Sales" },
  { name: "Orbadiah Wetherill", language: "Afrikaans", company: "Lazz", departure: "Engineering" },
  { name: "Winny Delieu", language: "Azerbaijani", company: "Avamm", departure: "Marketing" },
  { name: "Toby Pinnion", language: "Ojibwa", company: "Lazzy", departure: "Legal" },
  { name: "Thomasine Maycey", language: "Hiri Motu", company: "Blognation", departure: "Services" },
  { name: "Sinclare Byrnes", language: "Panjabi", company: "Centimia", departure: "Human Resources" },
  { name: "Farly Foster-Smith", language: "Sotho, Southern", company: "Shuffletag", departure: "Marketing" },
  { name: "Cedric Inggall", language: "Ndonga", company: "Lajo", departure: "Business Development" },
  { name: "Larissa Bradford", language: "Arabic", company: "Ntag", departure: "Human Resources" },
  { name: "Korie Fernandes", language: "Marshallese", company: "Centizu", departure: "Legal" },
  { name: "Fidelio Lattey", language: "Latvian", company: "Tagfeed", departure: "Product Management" },
  { name: "Ailina Moreton", language: "Turkish", company: "Browsezoom", departure: "Training" },
  { name: "Gilles Campanelli", language: "Bulgarian", company: "Wordware", departure: "Sales" },
  { name: "Tonye Whittuck", language: "Swati", company: "Linkbridge", departure: "Legal" },
  { name: "Charmaine Doers", language: "Bambara", company: "Latz", departure: "Marketing" },
  { name: "Wyndham Speight", language: "French", company: "Voomm", departure: "Sales" },
  { name: "Dulcia Grisenthwaite", language: "Tigrinya", company: "Skynoodle", departure: "Product Management" },
  { name: "Nealson Quinell", language: "Bosnian", company: "Flipopia", departure: "Product Management" },
  { name: "Faunie Runnalls", language: "Danish", company: "Twitternation", departure: "Support" },
  { name: "Herminia Raffin", language: "Indonesian", company: "Yodel", departure: "Human Resources" },
  { name: "Joya Berge", language: "Portuguese", company: "Zoomcast", departure: "Product Management" },
  { name: "Vina Mohan", language: "Kongo", company: "Tazz", departure: "Support" },
  { name: "Donica Biggin", language: "Marathi", company: "Jabbertype", departure: "Legal" },
  { name: "Nobe Towle", language: "Somali", company: "Jabbertype", departure: "Research and Development" },
  { name: "Dayna Van den Bosch", language: "Tatar", company: "Tavu", departure: "Accounting" },
  { name: "Gena Hendrik", language: "Sinhala", company: "Shufflester", departure: "Engineering" },
  { name: "Lyndell Overlow", language: "Serbian", company: "Feednation", departure: "Services" },
  { name: "Elinore Rainton", language: "Kashmiri", company: "Pixoboo", departure: "Legal" },
  { name: "Lin Bernardo", language: "Venda", company: "Jabbertype", departure: "Support" },
  { name: "Waldemar Crennell", language: "Kannada", company: "Trilia", departure: "Business Development" },
  { name: "Allistir Grocock", language: "Chamorro", company: "Mydeo", departure: "Human Resources" },
  { name: "Joyous Hamnett", language: "Bashkir", company: "Demizz", departure: "Support" },
  { name: "Dorie Whelband", language: "Irish", company: "Zazio", departure: "Human Resources" },
  { name: "Reynolds Orwin", language: "Hindi", company: "Bubblebox", departure: "Sales" },
  { name: "Lenci Malster", language: "Basque", company: "Zoomzone", departure: "Legal" },
  { name: "Valentine Ellery", language: "Hebrew", company: "Twitterbeat", departure: "Engineering" },
  { name: "Helaina Podbury", language: "Nauru", company: "Skivee", departure: "Marketing" },
  { name: "Cletis Bulcroft", language: "Quechua", company: "Mymm", departure: "Services" },
  { name: "August Harkus", language: "Corsican", company: "Jaxbean", departure: "Research and Development" },
  { name: "Callean Barnwell", language: "Tagalog", company: "Latz", departure: "Sales" },
  { name: "Benita Coke", language: "Telugu", company: "Centizu", departure: "Product Management" },
  { name: "Milicent Winchcomb", language: "Basque", company: "Myworks", departure: "Business Development" },
  { name: "Edee Bagnall", language: "Latvian", company: "Fliptune", departure: "Business Development" },
  { name: "Jules Mawby", language: "Nauru", company: "Viva", departure: "Training" },
  { name: "Becka Kings", language: "Galician", company: "Zoombeat", departure: "Support" },
  { name: "Manfred Morland", language: "Uzbek", company: "Yodel", departure: "Product Management" },
  { name: "Early Lothlorien", language: "Bengali", company: "Quamba", departure: "Support" },
  { name: "Morgan Leggs", language: "Chinese", company: "Feedfire", departure: "Support" },
  { name: "Bryanty Eble", language: "Italian", company: "Jayo", departure: "Engineering" },
  { name: "Waverly Shore", language: "Afrikaans", company: "Cogilith", departure: "Legal" },
  { name: "Garland Woodhead", language: "Hausa", company: "Topicblab", departure: "Engineering" },
  { name: "Missie Brandel", language: "Swedish", company: "Topicstorm", departure: "Sales" },
  { name: "Binni Pont", language: "Tibetan", company: "Oyoyo", departure: "Research and Development" },
  { name: "Alis Wornum", language: "Lao", company: "Roodel", departure: "Product Management" },
  { name: "Jessi Rodson", language: "Northern Sami", company: "Yabox", departure: "Legal" },
  { name: "Carri Eglin", language: "Chamorro", company: "Twitterwire", departure: "Research and Development" },
  { name: "Jareb Emmins", language: "Bosnian", company: "LiveZ", departure: "Business Development" },
  { name: "Gaelan Kibby", language: "Avaric", company: "LiveZ", departure: "Legal" },
  { name: "Donavon Guildford", language: "Albanian", company: "Talane", departure: "Sales" },
  { name: "Mahala Hember", language: "Pushto", company: "Skinder", departure: "Support" },
  { name: "Mathilde De Rye Barrett", language: "Panjabi", company: "Vinte", departure: "Engineering" },
  { name: "Tammy Roadknight", language: "Volapük", company: "Oyope", departure: "Business Development" },
  { name: "Ivett Kiely", language: "Luxembourgish", company: "Skipstorm", departure: "Support" },
  { name: "Cariotta Wakelin", language: "Western Frisian", company: "Voolith", departure: "Legal" },
  { name: "Corri Druhan", language: "Uzbek", company: "Buzzster", departure: "Legal" },
  { name: "Hermia Croall", language: "Uighur", company: "Twitterworks", departure: "Human Resources" },
  { name: "Paddy Rowthorne", language: "Tahitian", company: "Oyoloo", departure: "Services" },
  { name: "Madge Kyngdon", language: "Hausa", company: "Yotz", departure: "Support" },
  { name: "Lyndsie Seamans", language: "Ewe", company: "Realbuzz", departure: "Business Development" },
  { name: "Maud Emms", language: "Kurdish", company: "Meemm", departure: "Engineering" },
  { name: "Sawyere Purver", language: "Afrikaans", company: "Muxo", departure: "Engineering" },
  { name: "Filberto Schoales", language: "Bokmål, Norwegian", company: "Livetube", departure: "Accounting" },
  { name: "Nessy Hug", language: "Navajo", company: "Aimbu", departure: "Sales" },
  { name: "Stanislas Merrywether", language: "Tahitian", company: "Twitterbridge", departure: "Sales" },
  { name: "Anthony Creavan", language: "Afrikaans", company: "Divanoodle", departure: "Business Development" },
  { name: "Kory Ellington", language: "Icelandic", company: "Livetube", departure: "Human Resources" },
  { name: "Emogene Edel", language: "Lithuanian", company: "Mybuzz", departure: "Legal" },
  { name: "Penrod Fitzjohn", language: "Lithuanian", company: "Kaymbo", departure: "Services" },
  { name: "Che Shingles", language: "Georgian", company: "Demimbu", departure: "Services" },
  { name: "Clementia Dagnan", language: "Thai", company: "Kanoodle", departure: "Legal" },
  { name: "Dolores McClurg", language: "Indonesian", company: "Nlounge", departure: "Product Management" },
  { name: "Niall Fassum", language: "Luba-Katanga", company: "Twitterbeat", departure: "Training" },
  { name: "Genna Crunden", language: "Javanese", company: "Tagpad", departure: "Sales" },
  { name: "Lilias Jackways", language: "Urdu", company: "Eire", departure: "Training" },
  { name: "Flossi Netti", language: "Italian", company: "Thoughtsphere", departure: "Engineering" },
  { name: "Dalston Raynes", language: "Tsonga", company: "Brightdog", departure: "Accounting" },
  { name: "Sibeal Spatarul", language: "Akan", company: "Kaymbo", departure: "Marketing" },
  { name: "Barthel Messam", language: "Welsh", company: "Youbridge", departure: "Support" },
  { name: "Harmonia Miettinen", language: "Danish", company: "Aivee", departure: "Accounting" },
  { name: "Ida Zuanelli", language: "Samoan", company: "Kwimbee", departure: "Human Resources" },
  { name: "Harley Ashton", language: "Swahili", company: "Geba", departure: "Product Management" },
  { name: "Daron Osburn", language: "Indonesian", company: "Riffpath", departure: "Human Resources" },
  { name: "Kaila Taye", language: "Western Frisian", company: "Wordtune", departure: "Product Management" },
  { name: "Mikel Comazzo", language: "Danish", company: "Edgetag", departure: "Legal" },
  { name: "Mathilda Bridgwater", language: "Chinese", company: "Twitternation", departure: "Legal" },
  { name: "Anette Keneforde", language: "Gujarati", company: "Twitternation", departure: "Services" },
  { name: "Rowe Krishtopaittis", language: "Welsh", company: "Yodoo", departure: "Human Resources" },
  { name: "Berthe Vigus", language: "Twi", company: "Topdrive", departure: "Legal" },
  { name: "Toinette Duffan", language: "Oromo", company: "Jabberbean", departure: "Human Resources" },
  { name: "Randall Heggs", language: "Western Frisian", company: "Browsedrive", departure: "Engineering" },
  { name: "Leonie Cabble", language: "Sango", company: "Feednation", departure: "Marketing" },
  { name: "Rhody Scourgie", language: "Northern Sami", company: "Skiba", departure: "Marketing" },
  { name: "Jessalyn Stothard", language: "Hebrew", company: "Divanoodle", departure: "Training" },
  { name: "Berkly Van Halen", language: "Tahitian", company: "Vinder", departure: "Product Management" },
  { name: "Fredia Pain", language: "Malagasy", company: "Eimbee", departure: "Support" },
  { name: "Rubina Neasam", language: "Uzbek", company: "Skajo", departure: "Legal" },
  { name: "Gordon Pleaden", language: "Belarusian", company: "Vinte", departure: "Human Resources" },
  { name: "Harold Derby", language: "Igbo", company: "Youtags", departure: "Business Development" },
  { name: "Wilfred Peet", language: "Haitian", company: "Youbridge", departure: "Support" },
  { name: "Bliss Del Dello", language: "Venda", company: "Bubbletube", departure: "Business Development" },
  { name: "Erwin Bingley", language: "Luxembourgish", company: "Brainbox", departure: "Services" },
  { name: "Bruno Childes", language: "Twi", company: "Voonte", departure: "Business Development" },
  { name: "Thomasine Byrch", language: "Tahitian", company: "Thoughtbeat", departure: "Research and Development" },
  { name: "Torrance Prester", language: "Afrikaans", company: "Mynte", departure: "Legal" },
  { name: "Dael Berthelmot", language: "Norwegian Nynorsk", company: "Twitterwire", departure: "Engineering" },
  { name: "Wren Castagneri", language: "Herero", company: "Skidoo", departure: "Engineering" },
  { name: "Chance Favela", language: "Amharic", company: "Zoomlounge", departure: "Sales" },
  { name: "Enrichetta Mapstone", language: "Aragonese", company: "Midel", departure: "Engineering" },
  { name: "Quincy Fitzackerley", language: "Lao", company: "Zoomcast", departure: "Engineering" },
  { name: "Gay Clarkin", language: "Zhuang", company: "Realbuzz", departure: "Research and Development" },
  { name: "Luigi Tunsley", language: "German", company: "Twinder", departure: "Business Development" },
  { name: "Ailina Harvey", language: "Sango", company: "Npath", departure: "Marketing" },
  { name: "Iona Fortoun", language: "Afrikaans", company: "Yabox", departure: "Services" },
  { name: "Eugenius Brozek", language: "Romanian", company: "Meevee", departure: "Accounting" },
  { name: "Violet Bisset", language: "Persian", company: "Thoughtbridge", departure: "Training" },
  { name: "Gabbi Ethelstone", language: "Kuanyama", company: "Babbleset", departure: "Accounting" },
  { name: "Liesa Scrafton", language: "Arabic", company: "Jayo", departure: "Services" },
  { name: "Elisha Palk", language: "Spanish", company: "Bubblebox", departure: "Business Development" },
  { name: "Gill Ince", language: "Kinyarwanda", company: "Kwilith", departure: "Marketing" },
  { name: "Ulrica Fonquernie", language: "Norwegian Nynorsk", company: "Oodoo", departure: "Product Management" },
  { name: "Jazmin Olenichev", language: "Belarusian", company: "Voolith", departure: "Training" },
  { name: "Rowney Flips", language: "Manx", company: "Eazzy", departure: "Product Management" },
  { name: "Harriett Treweela", language: "Luxembourgish", company: "Yakidoo", departure: "Training" },
  { name: "Emalia Werrit", language: "Tibetan", company: "Divavu", departure: "Product Management" },
  { name: "Bessy Scardafield", language: "Russian", company: "Gabvine", departure: "Training" },
  { name: "Simmonds Pilmore", language: "Central Khmer", company: "Agimba", departure: "Services" },
  { name: "Thibaud Towers", language: "Korean", company: "Browsebug", departure: "Legal" },
  { name: "Eziechiele Rolfs", language: "Dutch", company: "Wikibox", departure: "Marketing" },
  { name: "Kittie Cason", language: "Swati", company: "Gabcube", departure: "Research and Development" },
  { name: "Wilmar Widger", language: "Xhosa", company: "Twiyo", departure: "Product Management" },
  { name: "Karyl Walsom", language: "Zhuang", company: "Quamba", departure: "Training" },
  { name: "Stormy Pearcehouse", language: "Vietnamese", company: "Meetz", departure: "Human Resources" },
  { name: "Andriette Maiden", language: "Ganda", company: "Gabcube", departure: "Training" },
  { name: "Olia Brinsden", language: "Bengali", company: "Twitterworks", departure: "Business Development" },
  { name: "Karry Hammant", language: "Kalaallisut", company: "Abatz", departure: "Human Resources" },
  { name: "Quinta Pidgeley", language: "Ido", company: "Leenti", departure: "Training" },
  { name: "Jaime Suddaby", language: "Urdu", company: "Livetube", departure: "Training" },
  { name: "Davita Iacovides", language: "Kinyarwanda", company: "Npath", departure: "Business Development" },
  { name: "Kendell McTear", language: "Ido", company: "Thoughtbeat", departure: "Engineering" },
  { name: "Bradney Tutill", language: "Lithuanian", company: "Lazz", departure: "Business Development" },
  { name: "Gregorio Grigoli", language: "Bengali", company: "Digitube", departure: "Support" },
  { name: "Hillier Clericoates", language: "Kurdish", company: "Chatterbridge", departure: "Support" },
  { name: "Merline Thirkettle", language: "Cree", company: "Skiptube", departure: "Human Resources" },
  { name: "Desmond Sammons", language: "Romansh", company: "Snaptags", departure: "Services" },
  { name: "Sal Boriston", language: "Danish", company: "Voonix", departure: "Training" },
  { name: "Bettine Duckers", language: "Haitian", company: "Realpoint", departure: "Human Resources" },
  { name: "Remy Davidovich", language: "Aragonese", company: "Nlounge", departure: "Human Resources" },
  { name: "Merline Bramer", language: "Esperanto", company: "Quimm", departure: "Engineering" },
  { name: "Lib Eadington", language: "Divehi", company: "Jabbercube", departure: "Product Management" },
  { name: "Yorker Webben", language: "Quechua", company: "Flashdog", departure: "Sales" },
  { name: "Abie Simecek", language: "Sichuan Yi", company: "Eabox", departure: "Services" },
  { name: "Katie Calderon", language: "Spanish", company: "Tanoodle", departure: "Business Development" },
  { name: "Benedicta Dicks", language: "Twi", company: "Kimia", departure: "Research and Development" },
  { name: "Bili Hanratty", language: "Esperanto", company: "Gigashots", departure: "Product Management" },
  { name: "Sigfrid Warbey", language: "Irish", company: "Meembee", departure: "Legal" },
  { name: "Jeri Peach", language: "Xhosa", company: "Gabtune", departure: "Engineering" },
  { name: "Shanie Chettoe", language: "Ganda", company: "Roombo", departure: "Product Management" },
  { name: "Eddi Blezard", language: "Malayalam", company: "Eire", departure: "Sales" },
  { name: "Sonia Dumphries", language: "Breton", company: "Meetz", departure: "Research and Development" },
  { name: "Gibbie Jakoviljevic", language: "Shona", company: "Twitterwire", departure: "Accounting" },
  { name: "Nara Diggles", language: "Komi", company: "Twiyo", departure: "Product Management" },
  { name: "Esdras Collington", language: "Galician", company: "Kwideo", departure: "Services" },
  { name: "Robinet Absolom", language: "Tamil", company: "Plajo", departure: "Business Development" },
  { name: "Sherill Gunton", language: "Kuanyama", company: "Abata", departure: "Business Development" },
  { name: "Isabeau Spinige", language: "Telugu", company: "Jetwire", departure: "Services" },
  { name: "Ernst Ponting", language: "Cornish", company: "Kwilith", departure: "Sales" },
  { name: "Eda Feast", language: "Ganda", company: "Thoughtsphere", departure: "Engineering" },
  { name: "Meridith Hought", language: "Pushto", company: "Mydeo", departure: "Services" },
  { name: "Christye Paffitt", language: "Ndebele, South", company: "Youspan", departure: "Business Development" },
  { name: "Jody Downe", language: "Assamese", company: "Gigaclub", departure: "Sales" },
  { name: "Darnall Leishman", language: "Albanian", company: "Livetube", departure: "Business Development" },
  { name: "Julio Sarfatti", language: "Latin", company: "Topicware", departure: "Sales" },
  { name: "Tomi Ledram", language: "Bambara", company: "Quire", departure: "Training" },
  { name: "Mandy Jaycock", language: "Chuvash", company: "Gigashots", departure: "Business Development" },
  { name: "Rupert Bottrill", language: "Uzbek", company: "Yata", departure: "Services" },
  { name: "Sauveur Glasspoole", language: "Zhuang", company: "Voonix", departure: "Product Management" },
  { name: "Kingston Grossman", language: "Spanish", company: "Divanoodle", departure: "Marketing" },
  { name: "Tiler Benns", language: "Interlingue", company: "Rhycero", departure: "Marketing" },
  { name: "Mile Gebhard", language: "Luba-Katanga", company: "Thoughtstorm", departure: "Sales" },
  { name: "Walsh Armer", language: "Limburgan", company: "Izio", departure: "Services" },
  { name: "Lucie Downage", language: "Limburgan", company: "Fivechat", departure: "Business Development" },
  { name: "Ahmed Knowler", language: "Persian", company: "Livepath", departure: "Legal" },
  { name: "Darby Meechan", language: "Kazakh", company: "Mycat", departure: "Business Development" },
  { name: "Arty Arrigo", language: "Danish", company: "Jatri", departure: "Support" },
  { name: "Irv Pickford", language: "Central Khmer", company: "Livetube", departure: "Support" },
  { name: "Calhoun Naisbet", language: "Kurdish", company: "Gabvine", departure: "Services" },
  { name: "Liesa Skeermor", language: "Kanuri", company: "Skimia", departure: "Research and Development" },
  { name: "Rusty Reolfo", language: "Spanish", company: "Lazz", departure: "Engineering" },
  { name: "Batsheva Cannan", language: "Xhosa", company: "Feedmix", departure: "Marketing" },
  { name: "Gerald McGhie", language: "Shona", company: "Lajo", departure: "Business Development" },
  { name: "Jerrome Oby", language: "Turkmen", company: "Muxo", departure: "Training" },
  { name: "Dacia Gremain", language: "Kurdish", company: "Flipstorm", departure: "Support" },
  { name: "Sisile Faichney", language: "Swahili", company: "Browseblab", departure: "Research and Development" },
  { name: "Shelba Hardington", language: "Uzbek", company: "Yombu", departure: "Marketing" },
  { name: "Florence Bafford", language: "Ndebele, South", company: "Leenti", departure: "Engineering" },
  { name: "Amalita Foulger", language: "Guarani", company: "Realcube", departure: "Business Development" },
  { name: "Yancey Lawday", language: "Urdu", company: "Innotype", departure: "Human Resources" },
  { name: "May Wickendon", language: "Nepali", company: "Mybuzz", departure: "Human Resources" },
  { name: "Demeter Boam", language: "Ndebele, North", company: "Brightdog", departure: "Engineering" },
  { name: "Bunny Croft", language: "Kanuri", company: "Muxo", departure: "Training" },
  { name: "Gwendolin Raymen", language: "Ossetian", company: "Oyoba", departure: "Marketing" },
  { name: "Candice Jenk", language: "Dzongkha", company: "Oyope", departure: "Sales" },
  { name: "Grange McRonald", language: "Lao", company: "Linkbuzz", departure: "Human Resources" },
  { name: "Marylynne Rye", language: "Pali", company: "Reallinks", departure: "Sales" },
  { name: "Emmey Mc Andrew", language: "Slovenian", company: "Skiba", departure: "Business Development" },
  { name: "Henriette Ambroziak", language: "Oromo", company: "Reallinks", departure: "Support" },
  { name: "Gertie Carnegie", language: "Occitan (post 1500)", company: "Mymm", departure: "Support" },
  { name: "Iris Christofides", language: "Pushto", company: "Skinix", departure: "Research and Development" },
  { name: "Eugenius Cremen", language: "Ewe", company: "Kwilith", departure: "Product Management" },
  { name: "Robinia Suddell", language: "Zulu", company: "Topicware", departure: "Accounting" },
  { name: "Hyacinthie Meighan", language: "Malay", company: "Jabbercube", departure: "Accounting" },
  { name: "Ulrikaumeko Yukhtin", language: "Turkish", company: "Trilith", departure: "Product Management" },
  { name: "Dotti Eade", language: "German", company: "Oyondu", departure: "Accounting" },
  { name: "Patin Fearey", language: "Hindi", company: "Quire", departure: "Business Development" },
  { name: "Kizzee Klesse", language: "Telugu", company: "Edgewire", departure: "Services" },
  { name: "Lanie Carman", language: "Bulgarian", company: "Avamm", departure: "Sales" },
  { name: "Valentijn Perrington", language: "Norwegian Nynorsk", company: "Eimbee", departure: "Product Management" },
  { name: "Valera Tremellier", language: "Catalan", company: "Linkbridge", departure: "Product Management" },
  { name: "Ilysa Parslow", language: "Limburgan", company: "Demivee", departure: "Engineering" },
  { name: "Rafferty Kernoghan", language: "Turkish", company: "Dynabox", departure: "Business Development" },
  { name: "Gregg Fensome", language: "Dzongkha", company: "JumpXS", departure: "Research and Development" },
  { name: "Amalee Mohammad", language: "Estonian", company: "Babblestorm", departure: "Research and Development" },
  { name: "Bianca Conford", language: "Persian", company: "Twimm", departure: "Training" },
  { name: "Berni Sweed", language: "Nauru", company: "Divanoodle", departure: "Support" },
  { name: "Alessandra Hessle", language: "Maori", company: "Vinder", departure: "Legal" },
  { name: "Tod Cristofolini", language: "Aragonese", company: "Bubbletube", departure: "Accounting" },
  { name: "Suzy Cookley", language: "Divehi", company: "Skyndu", departure: "Business Development" },
  { name: "Flore Fouch", language: "Kashmiri", company: "Tagfeed", departure: "Legal" },
  { name: "Samuele Colten", language: "Greek, Modern (1453-)", company: "Zoombox", departure: "Marketing" },
  { name: "Arluene Maddison", language: "Indonesian", company: "Fivebridge", departure: "Research and Development" },
  { name: "Hesther Crosskill", language: "Fulah", company: "Abata", departure: "Engineering" },
  { name: "Carita Tissiman", language: "Yoruba", company: "Agimba", departure: "Training" },
  { name: "Prissie Stannah", language: "Javanese", company: "Mynte", departure: "Accounting" },
  { name: "Bond Trevethan", language: "Norwegian Nynorsk", company: "Feedfish", departure: "Business Development" },
  { name: "Janaya Starbeck", language: "Ndebele, South", company: "Babbleblab", departure: "Sales" },
  { name: "Arlen Glauber", language: "Hungarian", company: "Rhynoodle", departure: "Accounting" },
  { name: "Shauna Kinner", language: "Greek, Modern (1453-)", company: "Fliptune", departure: "Business Development" },
  { name: "Douglass Ghidelli", language: "Tibetan", company: "Livetube", departure: "Legal" },
  { name: "Hobie Preto", language: "Marshallese", company: "Minyx", departure: "Human Resources" },
  { name: "Maryjane Eisold", language: "Hausa", company: "Gigaclub", departure: "Engineering" },
  { name: "Rosalynd Panther", language: "Japanese", company: "Divape", departure: "Engineering" },
  { name: "Brander Ofield", language: "Japanese", company: "Bluejam", departure: "Training" },
  { name: "Angie Dandison", language: "Avestan", company: "Edgepulse", departure: "Engineering" },
  { name: "Lidia Tommeo", language: "Tsonga", company: "Rhynyx", departure: "Support" },
  { name: "Hiram Tape", language: "Pushto", company: "Rhycero", departure: "Engineering" },
  { name: "Modestine Humbles", language: "Fijian", company: "Dabtype", departure: "Legal" },
  { name: "Sollie Muino", language: "Estonian", company: "Yakitri", departure: "Legal" },
  { name: "Bastien McGiffie", language: "Tamil", company: "Skyble", departure: "Accounting" },
  { name: "Ninette Baumford", language: "Komi", company: "Yacero", departure: "Services" },
  { name: "Bevan Yeaman", language: "Luxembourgish", company: "Feedfire", departure: "Accounting" },
  { name: "Pauly Birkinshaw", language: "Hausa", company: "Einti", departure: "Human Resources" },
  { name: "Monty Beumant", language: "Javanese", company: "Jayo", departure: "Training" },
  { name: "Samson Bavister", language: "Croatian", company: "Flipopia", departure: "Human Resources" },
  { name: "Patrizio Deluze", language: "Bosnian", company: "Thoughtbridge", departure: "Accounting" },
  { name: "Corie Standon", language: "Turkish", company: "Twitterlist", departure: "Business Development" },
  { name: "Xenos Mulrenan", language: "Aragonese", company: "Twinder", departure: "Human Resources" },
  { name: "Melonie Vivash", language: "Nauru", company: "Meevee", departure: "Business Development" },
  { name: "Reinhard Vamplew", language: "Norwegian", company: "Linkbridge", departure: "Engineering" },
  { name: "Harper World", language: "Interlingue", company: "Brightdog", departure: "Human Resources" },
  { name: "Willdon Pauley", language: "Arabic", company: "Photofeed", departure: "Accounting" },
  { name: "Towney Di Roberto", language: "Irish", company: "Photofeed", departure: "Sales" },
  { name: "Grier Prestage", language: "Guarani", company: "Meezzy", departure: "Sales" },
  { name: "Devlin Hauxby", language: "Ndonga", company: "Blognation", departure: "Marketing" },
  { name: "Isidoro Bonney", language: "Manx", company: "Skyndu", departure: "Business Development" },
  { name: "Murdock Jurczyk", language: "Komi", company: "Skidoo", departure: "Training" },
  { name: "Brandais McKinnell", language: "French", company: "Fivebridge", departure: "Human Resources" },
  { name: "Bride Terrey", language: "Tamil", company: "Browsetype", departure: "Business Development" },
  { name: "Agatha Perrelli", language: "Welsh", company: "Voonyx", departure: "Product Management" },
  { name: "Nicholle Hatry", language: "Tajik", company: "Quinu", departure: "Product Management" },
  { name: "Ange Chandlar", language: "Telugu", company: "Photobean", departure: "Engineering" },
  { name: "Sollie Vardey", language: "Sundanese", company: "Wordify", departure: "Engineering" },
  { name: "Idell McAvinchey", language: "Interlingua (International Auxiliary Language Association)", company: "Realbridge", departure: "Training" },
  { name: "Ariella Impey", language: "Oromo", company: "Tagtune", departure: "Sales" },
  { name: "Cad Ions", language: "Bashkir", company: "Oyoloo", departure: "Research and Development" },
  { name: "Reece Sawter", language: "Rundi", company: "Zoombox", departure: "Engineering" },
  { name: "Vassili Boulder", language: "Aragonese", company: "Linktype", departure: "Training" },
  { name: "Vladamir Pull", language: "Zhuang", company: "Avamm", departure: "Business Development" },
  { name: "Lillian MacCoughen", language: "Cornish", company: "Nlounge", departure: "Product Management" },
  { name: "Isaak Smaridge", language: "Haitian", company: "Yata", departure: "Training" },
  { name: "Lanette Bugby", language: "Hindi", company: "Voonix", departure: "Legal" },
  { name: "Cyndy Zottoli", language: "Walloon", company: "Jayo", departure: "Human Resources" },
  { name: "Katrina Louw", language: "Wolof", company: "Tavu", departure: "Sales" },
  { name: "Peirce Del Checolo", language: "Kirghiz", company: "Aimbu", departure: "Training" },
  { name: "Melisent Denholm", language: "German", company: "Pixope", departure: "Engineering" },
  { name: "Chaddie Woodgate", language: "Cornish", company: "Photofeed", departure: "Research and Development" },
  { name: "Thorpe Garretson", language: "Interlingue", company: "Kwimbee", departure: "Training" },
  { name: "Cordi Dalliwatr", language: "Shona", company: "Jayo", departure: "Services" },
  { name: "Clifford Keirle", language: "Welsh", company: "Pixoboo", departure: "Engineering" },
  { name: "Olimpia Holbury", language: "Xhosa", company: "Aivee", departure: "Services" },
  { name: "Nichols Aldwick", language: "Ewe", company: "Mudo", departure: "Product Management" },
  { name: "Lodovico Weinberg", language: "Sotho, Southern", company: "Zava", departure: "Services" },
  { name: "Conni Croce", language: "Kikuyu", company: "Latz", departure: "Legal" },
  { name: "Basile Bittlestone", language: "Tatar", company: "Roomm", departure: "Product Management" },
  { name: "Cirillo Behrend", language: "Marshallese", company: "Viva", departure: "Sales" },
  { name: "Lyndel Bimson", language: "Spanish", company: "Pixoboo", departure: "Training" },
  { name: "Malory Neilands", language: "Malagasy", company: "Flashspan", departure: "Services" },
  { name: "Rita Rook", language: "Urdu", company: "Dynabox", departure: "Accounting" },
  { name: "Tirrell Pattenden", language: "Nauru", company: "Skyba", departure: "Business Development" },
  { name: "Pierrette Quye", language: "Javanese", company: "Rhyzio", departure: "Human Resources" },
  { name: "Misty Punt", language: "Ndonga", company: "Jaxworks", departure: "Product Management" },
  { name: "Verena Playfoot", language: "Sango", company: "Eamia", departure: "Product Management" },
  { name: "Ring Jurs", language: "Danish", company: "Thoughtstorm", departure: "Engineering" },
  { name: "Jolynn Wooder", language: "Aymara", company: "Gabvine", departure: "Legal" },
  { name: "Wynny Andreuzzi", language: "Navajo", company: "Dynabox", departure: "Services" },
  { name: "Lennie Dohmann", language: "Occitan (post 1500)", company: "Flashspan", departure: "Training" },
  { name: "Agnola Grodden", language: "Yoruba", company: "Rhynyx", departure: "Accounting" },
  { name: "Heriberto Giovani", language: "Armenian", company: "Skinte", departure: "Human Resources" },
  { name: "Portie Howling", language: "Armenian", company: "Eadel", departure: "Human Resources" },
  { name: "Josee Humpatch", language: "Oromo", company: "Linklinks", departure: "Legal" },
  { name: "Angel Downing", language: "Occitan (post 1500)", company: "Buzzdog", departure: "Legal" },
  { name: "Rubetta Caldwall", language: "Sotho, Southern", company: "Rhyzio", departure: "Product Management" },
  { name: "Marjorie Plaice", language: "Norwegian", company: "Skimia", departure: "Support" },
  { name: "Douglass MacKilroe", language: "Rundi", company: "Zava", departure: "Human Resources" },
  { name: "Adelle Unsworth", language: "Hausa", company: "Skimia", departure: "Legal" },
  { name: "Ardyce Ebbens", language: "Tonga (Tonga Islands)", company: "Avamm", departure: "Research and Development" },
  { name: "Winthrop Birth", language: "Kannada", company: "Gabvine", departure: "Business Development" },
  { name: "Wake Adamiec", language: "Inuktitut", company: "Jatri", departure: "Marketing" },
  { name: "Bank Gilliatt", language: "Belarusian", company: "Wordify", departure: "Marketing" },
  { name: "Marco Dewfall", language: "Burmese", company: "Ozu", departure: "Accounting" },
  { name: "Leslie Turn", language: "Inuktitut", company: "Thoughtsphere", departure: "Business Development" },
  { name: "Fan Rief", language: "Malayalam", company: "Demizz", departure: "Product Management" },
  { name: "Daniela Flatte", language: "Sango", company: "Quaxo", departure: "Training" },
  { name: "Estrellita Capstaff", language: "Nauru", company: "Babbleblab", departure: "Engineering" },
  { name: "Alfred Hustings", language: "Avestan", company: "Dabjam", departure: "Support" },
  { name: "Gus Robion", language: "Bulgarian", company: "Skyndu", departure: "Sales" },
  { name: "Whitney Malthouse", language: "Kirghiz", company: "Twimm", departure: "Training" },
  { name: "Lorant Chill", language: "Lithuanian", company: "Skinix", departure: "Marketing" },
  { name: "Pattie Grinikhin", language: "Malay", company: "Oloo", departure: "Product Management" },
  { name: "Alexandrina Bruyns", language: "Tsonga", company: "Photofeed", departure: "Training" },
  { name: "Rodrick Hebbard", language: "Maori", company: "Zava", departure: "Legal" },
  { name: "Addison Garett", language: "Abkhazian", company: "Meevee", departure: "Services" },
  { name: "Augy Bonnyson", language: "Belarusian", company: "Agivu", departure: "Human Resources" },
  { name: "Alicia Rushforth", language: "Pushto", company: "Tavu", departure: "Human Resources" },
  { name: "Giffer MacMichael", language: "Azerbaijani", company: "Innojam", departure: "Training" },
  { name: "Candi Irving", language: "Dzongkha", company: "Kazu", departure: "Marketing" },
  { name: "Felicia Josipovic", language: "Yoruba", company: "Jazzy", departure: "Product Management" },
  { name: "Joell Carnachen", language: "Limburgan", company: "Quimm", departure: "Training" },
  { name: "Quinta Fitzsimons", language: "Samoan", company: "Livetube", departure: "Support" },
  { name: "Michaeline Diboll", language: "Uighur", company: "Yombu", departure: "Product Management" },
  { name: "Kendra Elfes", language: "Turkish", company: "Topiclounge", departure: "Accounting" },
  { name: "Dniren Jackman", language: "Wolof", company: "Oyoyo", departure: "Business Development" },
  { name: "Daffy Cleall", language: "Danish", company: "Topdrive", departure: "Support" },
  { name: "Katti Rowbrey", language: "Spanish", company: "Katz", departure: "Sales" },
  { name: "Lorenza Retchford", language: "Avestan", company: "Zoonder", departure: "Human Resources" },
  { name: "Garvy Slaney", language: "French", company: "Realbridge", departure: "Training" },
  { name: "Grace Maultby", language: "Oromo", company: "Gigashots", departure: "Accounting" },
  { name: "Burch Frosdick", language: "Chechen", company: "Gabvine", departure: "Research and Development" },
  { name: "Forbes Kobu", language: "Irish", company: "Aimbo", departure: "Legal" },
  { name: "Becki Hopewell", language: "Czech", company: "Skyndu", departure: "Services" },
  { name: "Othilia Tape", language: "Belarusian", company: "Realfire", departure: "Human Resources" },
  { name: "Yasmeen Notton", language: "Kalaallisut", company: "Topiczoom", departure: "Accounting" },
  { name: "Georgy Kirman", language: "Telugu", company: "Feedmix", departure: "Marketing" },
  { name: "Mame Mcmanaman", language: "Bislama", company: "Quamba", departure: "Business Development" },
  { name: "Ernaline Saggs", language: "Marshallese", company: "Jetpulse", departure: "Product Management" },
  { name: "Corbin Keri", language: "Vietnamese", company: "Oozz", departure: "Accounting" },
  { name: "Ellene Roberti", language: "Chinese", company: "Yombu", departure: "Services" },
  { name: "Alecia Sparrowe", language: "Panjabi", company: "Quire", departure: "Services" },
  { name: "Fey Trathan", language: "Panjabi", company: "Meeveo", departure: "Research and Development" },
  { name: "Zonda Hattigan", language: "Tagalog", company: "Kimia", departure: "Legal" },
  { name: "Tandie Zohrer", language: "Pushto", company: "Dynabox", departure: "Accounting" },
  { name: "Carmita Endicott", language: "Somali", company: "Thoughtstorm", departure: "Legal" },
  { name: "Georgeanne Iwanowicz", language: "Fulah", company: "Realbuzz", departure: "Training" },
  { name: "Nikita Duke", language: "Church Slavic", company: "Kimia", departure: "Training" },
  { name: "Even Roofe", language: "Estonian", company: "Skivee", departure: "Training" },
  { name: "Simon Pearcy", language: "Gujarati", company: "BlogXS", departure: "Training" },
  { name: "Magdalen Corney", language: "English", company: "Aivee", departure: "Research and Development" },
  { name: "Malissa Wastell", language: "Fijian", company: "Eare", departure: "Legal" },
  { name: "Bridie Bubbins", language: "Malayalam", company: "Demimbu", departure: "Sales" },
  { name: "Colline Tourne", language: "Herero", company: "Blogpad", departure: "Support" },
  { name: "Dionisio Rodda", language: "Malagasy", company: "Skiptube", departure: "Human Resources" },
  { name: "Duke Atkin", language: "Gujarati", company: "Brainlounge", departure: "Accounting" },
  { name: "Martha Somner", language: "Tibetan", company: "Mybuzz", departure: "Training" },
  { name: "Odie Duncan", language: "Interlingua (International Auxiliary Language Association)", company: "Topiclounge", departure: "Human Resources" },
  { name: "Brnaba Shevell", language: "Slovak", company: "Livefish", departure: "Training" },
  { name: "Ced Gartside", language: "Ukrainian", company: "Pixoboo", departure: "Sales" },
  { name: "Lannie Cleaton", language: "Afar", company: "Flashpoint", departure: "Training" },
  { name: "Barbey Grigoryov", language: "Bulgarian", company: "Voonte", departure: "Accounting" },
  { name: "Ignace Puckett", language: "Italian", company: "Feedbug", departure: "Research and Development" },
  { name: "Elnora McTague", language: "Inupiaq", company: "Devbug", departure: "Marketing" },
  { name: "Melli Bladen", language: "Latvian", company: "Innojam", departure: "Research and Development" },
  { name: "Evangelina Fullard", language: "French", company: "Twitterwire", departure: "Training" },
  { name: "Ephraim Jenkison", language: "Haitian", company: "BlogXS", departure: "Human Resources" },
  { name: "Darnall Waything", language: "Hiri Motu", company: "Devbug", departure: "Human Resources" },
  { name: "Parker Fiander", language: "Dzongkha", company: "Flipbug", departure: "Accounting" },
  { name: "Casandra Southwood", language: "Polish", company: "Topicshots", departure: "Human Resources" },
  { name: "Gerrie Farish", language: "Aymara", company: "Centidel", departure: "Engineering" },
  { name: "Glynn Overstone", language: "Thai", company: "Feednation", departure: "Research and Development" },
  { name: "Godfry Moorman", language: "Panjabi", company: "Bluejam", departure: "Product Management" },
  { name: "Kiel Miners", language: "Albanian", company: "Thoughtstorm", departure: "Business Development" },
  { name: "Ancell Jozef", language: "Ndonga", company: "Dabfeed", departure: "Support" },
  { name: "Fawnia Dubock", language: "Chinese", company: "Fliptune", departure: "Product Management" },
  { name: "Odetta Thresher", language: "Indonesian", company: "Twimm", departure: "Product Management" },
  { name: "Poppy Portman", language: "Sundanese", company: "Realbuzz", departure: "Legal" },
  { name: "Petronella Vallerine", language: "Inuktitut", company: "Zoombeat", departure: "Accounting" },
  { name: "Terrie Brisland", language: "Samoan", company: "Wikibox", departure: "Legal" },
  { name: "Bebe Balsillie", language: "Marshallese", company: "Youopia", departure: "Sales" },
  { name: "Kerrin Froude", language: "Thai", company: "Gabvine", departure: "Legal" },
  { name: "Jillayne Boobyer", language: "Maori", company: "Thoughtbeat", departure: "Engineering" },
  { name: "Gothart Orteau", language: "Luxembourgish", company: "Skibox", departure: "Human Resources" },
  { name: "Pepe Solman", language: "Northern Sami", company: "Photospace", departure: "Product Management" },
  { name: "Brucie Liverock", language: "Finnish", company: "Youopia", departure: "Engineering" },
  { name: "Walt Takle", language: "Walloon", company: "Flipopia", departure: "Legal" },
  { name: "Laural Illingsworth", language: "Kinyarwanda", company: "Topicshots", departure: "Engineering" },
  { name: "Cam Rathmell", language: "Tonga (Tonga Islands)", company: "Jaloo", departure: "Business Development" },
  { name: "Cointon Falconbridge", language: "Bosnian", company: "Cogidoo", departure: "Product Management" },
  { name: "Austine Antoniazzi", language: "Oromo", company: "Lajo", departure: "Accounting" },
  { name: "Gleda Motton", language: "Swati", company: "Dablist", departure: "Accounting" },
  { name: "Hamnet MacKall", language: "Cornish", company: "Npath", departure: "Research and Development" },
  { name: "Leon Domelow", language: "Vietnamese", company: "LiveZ", departure: "Marketing" },
  { name: "Gerta Gillions", language: "Albanian", company: "Miboo", departure: "Marketing" },
  { name: "Shea Tennet", language: "Mongolian", company: "Zoonder", departure: "Business Development" },
  { name: "Fidelity McDonough", language: "Kazakh", company: "Linkbuzz", departure: "Marketing" },
  { name: "Marleen Buckthorpe", language: "Maori", company: "Yozio", departure: "Sales" },
  { name: "Lindsey Gingel", language: "Slovenian", company: "Divanoodle", departure: "Research and Development" },
  { name: "Frederico Daniele", language: "Haitian", company: "Vinder", departure: "Research and Development" },
  { name: "Bernete Birks", language: "Nauru", company: "Gabtype", departure: "Business Development" },
  { name: "Nikolai Monaghan", language: "Marathi", company: "Flipstorm", departure: "Research and Development" },
  { name: "Jyoti Finnis", language: "Cree", company: "Ailane", departure: "Services" },
  { name: "Reinwald Jammet", language: "Somali", company: "Innotype", departure: "Training" },
  { name: "Nev Kuhwald", language: "Haitian", company: "Dynabox", departure: "Research and Development" },
  { name: "Eadie Salzburg", language: "Lingala", company: "Avamm", departure: "Product Management" },
  { name: "Bernetta Braybrookes", language: "Lingala", company: "Feednation", departure: "Marketing" },
  { name: "Cybill Pennings", language: "Kikuyu", company: "Brightbean", departure: "Support" },
  { name: "Randal Glyn", language: "Uighur", company: "Kwimbee", departure: "Business Development" },
  { name: "Nancie Wolsey", language: "Corsican", company: "Skyba", departure: "Support" },
  { name: "Elli Daice", language: "Fijian", company: "Twitterbridge", departure: "Training" },
  { name: "Paule Denford", language: "Indonesian", company: "Tambee", departure: "Legal" },
  { name: "Vinnie Barthorpe", language: "Interlingue", company: "Yakijo", departure: "Product Management" },
  { name: "Cyrus Deighan", language: "Irish", company: "Tavu", departure: "Support" },
  { name: "Hashim Jentin", language: "Inuktitut", company: "Eamia", departure: "Sales" },
  { name: "Wilmar Margiotta", language: "Uighur", company: "Topicblab", departure: "Product Management" },
  { name: "Savina Formoy", language: "Dzongkha", company: "Einti", departure: "Services" },
  { name: "Jeannie Juschka", language: "Japanese", company: "Skyvu", departure: "Sales" },
  { name: "Skylar Chevin", language: "Fijian", company: "Edgeclub", departure: "Business Development" },
  { name: "Oralie Torrecilla", language: "Georgian", company: "Jayo", departure: "Accounting" },
  { name: "Cayla Fadden", language: "Mongolian", company: "Demimbu", departure: "Marketing" },
  { name: "Klaus Clayborn", language: "Korean", company: "Avavee", departure: "Human Resources" },
  { name: "Sande Mugford", language: "Turkmen", company: "Eayo", departure: "Marketing" },
  { name: "Thomas Alaway", language: "Avaric", company: "Vitz", departure: "Product Management" },
  { name: "Patrizius Sheilds", language: "Norwegian Nynorsk", company: "Fliptune", departure: "Training" },
  { name: "Burnaby Charlton", language: "Marshallese", company: "Brightdog", departure: "Accounting" },
  { name: "Tallie Brugden", language: "Malayalam", company: "Divavu", departure: "Product Management" },
  { name: "John Hayball", language: "Uighur", company: "Bubbletube", departure: "Legal" },
  { name: "Verine Reddle", language: "Kalaallisut", company: "Babbleopia", departure: "Legal" },
  { name: "Bourke Rimmer", language: "Northern Sami", company: "Twinder", departure: "Support" },
  { name: "Anne McCrossan", language: "Kurdish", company: "Roomm", departure: "Product Management" },
  { name: "Raychel Gland", language: "Inupiaq", company: "Shufflester", departure: "Human Resources" },
  { name: "Sonnnie Treeby", language: "Arabic", company: "Zoonder", departure: "Engineering" },
  { name: "Malina O' Flaherty", language: "Tatar", company: "Mynte", departure: "Sales" },
  { name: "Saba Wicher", language: "Bashkir", company: "Twitternation", departure: "Marketing" },
  { name: "Stephana Bustard", language: "Greek, Modern (1453-)", company: "Dynava", departure: "Human Resources" },
  { name: "Art Peetermann", language: "Afar", company: "Leenti", departure: "Legal" },
  { name: "Moreen Benthall", language: "Limburgan", company: "Flipstorm", departure: "Sales" },
  { name: "Hillel Tinham", language: "Corsican", company: "Devpoint", departure: "Sales" },
  { name: "Sigfrid Madgin", language: "Norwegian Nynorsk", company: "Voonyx", departure: "Human Resources" },
  { name: "Wye Pancost", language: "Arabic", company: "Twimm", departure: "Sales" },
  { name: "Fleurette Laye", language: "Romanian", company: "Dynabox", departure: "Marketing" },
  { name: "Ingram Taree", language: "Oriya", company: "Browsezoom", departure: "Business Development" },
  { name: "Saunders Oakeshott", language: "Corsican", company: "Vinder", departure: "Engineering" },
  { name: "Lauretta Greguoli", language: "Amharic", company: "Devbug", departure: "Research and Development" },
  { name: "Kizzie Jakuszewski", language: "Assamese", company: "Kimia", departure: "Services" },
  { name: "Joya Pentycross", language: "Kashmiri", company: "Cogilith", departure: "Research and Development" },
  { name: "Yves Zute", language: "Faroese", company: "Trilith", departure: "Product Management" },
  { name: "Trstram Ickowicz", language: "Hebrew", company: "Brightdog", departure: "Human Resources" },
  { name: "Madelina Venn", language: "Sichuan Yi", company: "Chatterbridge", departure: "Business Development" },
  { name: "Kati Garret", language: "Persian", company: "Meezzy", departure: "Sales" },
  { name: "Hasty Peirone", language: "Gaelic", company: "Skibox", departure: "Engineering" },
  { name: "Flore Phillipps", language: "Central Khmer", company: "Zoombeat", departure: "Product Management" },
  { name: "Yolane Asmus", language: "Ndebele, North", company: "Roombo", departure: "Research and Development" },
  { name: "Prentiss Normansell", language: "Tswana", company: "Tazz", departure: "Research and Development" },
  { name: "Hollyanne Filimore", language: "Swedish", company: "Devcast", departure: "Research and Development" },
  { name: "Gennifer Haslock(e)", language: "Gujarati", company: "Livetube", departure: "Sales" },
  { name: "Katy Waind", language: "Ewe", company: "Bluejam", departure: "Marketing" },
  { name: "Humfrey Leckenby", language: "Akan", company: "Tanoodle", departure: "Training" },
  { name: "Harmonie Habbeshaw", language: "Inupiaq", company: "Skaboo", departure: "Product Management" },
  { name: "Dionisio Rowbottom", language: "Marathi", company: "Ainyx", departure: "Accounting" },
  { name: "Gertie Bursnoll", language: "Inupiaq", company: "Babbleblab", departure: "Support" },
  { name: "Cy Rosedale", language: "Macedonian", company: "Topicblab", departure: "Engineering" },
  { name: "Udale Critchard", language: "Fulah", company: "Yombu", departure: "Sales" },
  { name: "Georgianne Bigmore", language: "Venda", company: "Divape", departure: "Engineering" },
  { name: "Paulo De Mico", language: "Oromo", company: "Kwilith", departure: "Business Development" },
  { name: "Dorothee Gumery", language: "Hungarian", company: "Bubbletube", departure: "Business Development" },
  { name: "Barret Caldaro", language: "Azerbaijani", company: "Gigashots", departure: "Legal" },
  { name: "Ulrica McMillan", language: "Lao", company: "Edgeify", departure: "Business Development" },
  { name: "Gabie Sunner", language: "Kurdish", company: "Aibox", departure: "Sales" },
  { name: "Tris Dronsfield", language: "Sanskrit", company: "Kwilith", departure: "Research and Development" },
  { name: "Cecilius Boice", language: "Mongolian", company: "Wikizz", departure: "Legal" },
  { name: "Kimble Janssen", language: "Sotho, Southern", company: "Yabox", departure: "Accounting" },
  { name: "Johanna Gleder", language: "Yiddish", company: "Cogilith", departure: "Accounting" },
  { name: "Holmes Mangeon", language: "Basque", company: "Wordify", departure: "Services" },
  { name: "Lyon Rosebotham", language: "Sichuan Yi", company: "Linkbridge", departure: "Training" },
  { name: "Karleen Ales0", language: "Abkhazian", company: "Roodel", departure: "Engineering" },
  { name: "Brooks Lumsdale", language: "Gujarati", company: "Skyble", departure: "Services" },
  { name: "Kris Bryde", language: "Central Khmer", company: "Feedfire", departure: "Sales" },
  { name: "Milicent Alexandre", language: "Luxembourgish", company: "Skipfire", departure: "Human Resources" },
  { name: "Thorpe Willox", language: "Sardinian", company: "Kare", departure: "Product Management" },
  { name: "Trey Dunkersley", language: "Volapük", company: "Omba", departure: "Human Resources" },
  { name: "Stevy McArthur", language: "Kannada", company: "Twitterwire", departure: "Research and Development" },
  { name: "Stevie Janouch", language: "Kongo", company: "Thoughtblab", departure: "Accounting" },
  { name: "Ddene Dawby", language: "Slovenian", company: "Feedbug", departure: "Marketing" },
  { name: "Frederich Lorenz", language: "Herero", company: "Skimia", departure: "Marketing" },
  { name: "Germaine Croot", language: "Ndebele, South", company: "Skajo", departure: "Research and Development" },
  { name: "Jaime Pentland", language: "Lao", company: "Youbridge", departure: "Sales" },
  { name: "Dorolice Reace", language: "Pali", company: "Kazu", departure: "Accounting" },
  { name: "Minnie Vasiliu", language: "Bengali", company: "Demivee", departure: "Product Management" },
  { name: "Aeriel Smallacombe", language: "Tagalog", company: "Thoughtbeat", departure: "Support" },
  { name: "Wallache Eveleigh", language: "Igbo", company: "Realfire", departure: "Product Management" },
  { name: "Gael Cordell", language: "Latin", company: "Twitterbridge", departure: "Sales" },
  { name: "Inglis Slaight", language: "Swahili", company: "Gigazoom", departure: "Services" },
  { name: "Ronnica Weddeburn", language: "Luxembourgish", company: "Edgeclub", departure: "Legal" },
  { name: "Ash Billo", language: "Chuvash", company: "Voolia", departure: "Business Development" },
  { name: "Katine Iddons", language: "Turkmen", company: "Centidel", departure: "Human Resources" },
  { name: "Ardelia Pettican", language: "Uzbek", company: "Photobug", departure: "Support" },
  { name: "Vicki Urian", language: "Luxembourgish", company: "Realcube", departure: "Legal" },
  { name: "Jillian Ivamy", language: "Burmese", company: "Centizu", departure: "Support" },
  { name: "Lory Cherryman", language: "Vietnamese", company: "Browseblab", departure: "Accounting" },
  { name: "Pru Thorsby", language: "Azerbaijani", company: "Oloo", departure: "Training" },
  { name: "Esta Berthome", language: "Sardinian", company: "Topicware", departure: "Marketing" },
  { name: "Raimondo Fackney", language: "Maori", company: "Camimbo", departure: "Training" },
  { name: "Nellie Haslock", language: "Esperanto", company: "Ailane", departure: "Sales" },
  { name: "Cherise Caesman", language: "Hungarian", company: "Dabvine", departure: "Legal" },
  { name: "Maddy Dedam", language: "Quechua", company: "Shuffletag", departure: "Product Management" },
  { name: "Teresa Suttling", language: "Fijian", company: "Livefish", departure: "Marketing" },
  { name: "Carlyn Casajuana", language: "Afar", company: "Riffwire", departure: "Marketing" },
  { name: "Valentia Hachard", language: "Tibetan", company: "Kwilith", departure: "Product Management" },
  { name: "Sandy Honatsch", language: "Macedonian", company: "Brightdog", departure: "Human Resources" },
  { name: "Leonore Garrat", language: "Sinhala", company: "Twitterlist", departure: "Engineering" },
  { name: "Nickey Rosenthaler", language: "Ido", company: "Demizz", departure: "Accounting" },
  { name: "Trenton Hubbins", language: "Javanese", company: "Trupe", departure: "Legal" },
  { name: "Chrystal Hedderly", language: "Igbo", company: "Skiba", departure: "Support" },
  { name: "Maynard Manketell", language: "Spanish", company: "Meedoo", departure: "Legal" },
  { name: "Tyne Caistor", language: "Welsh", company: "Quatz", departure: "Research and Development" },
  { name: "Robena Bettenson", language: "Maori", company: "Kamba", departure: "Product Management" },
  { name: "Hunter Batten", language: "French", company: "Layo", departure: "Support" },
  { name: "Thorstein Friedank", language: "Hausa", company: "Youtags", departure: "Marketing" },
  { name: "Rip Compson", language: "Fulah", company: "Vinder", departure: "Human Resources" },
  { name: "Terry Samweyes", language: "Georgian", company: "Linklinks", departure: "Product Management" },
  { name: "Adah Rattenbury", language: "Burmese", company: "Brainbox", departure: "Business Development" },
  { name: "Todd Daice", language: "English", company: "Skyndu", departure: "Support" },
  { name: "Celesta Creighton", language: "Assamese", company: "Vinte", departure: "Research and Development" },
  { name: "Job O'Hanley", language: "French", company: "Jabbercube", departure: "Support" },
  { name: "Drusie Welchman", language: "Croatian", company: "Voonix", departure: "Marketing" },
  { name: "Chelsea Hovy", language: "Vietnamese", company: "Feedfire", departure: "Human Resources" },
  { name: "Addison Lewisham", language: "Bulgarian", company: "Riffpath", departure: "Services" },
  { name: "Lynda Antham", language: "Venda", company: "Yodo", departure: "Sales" },
  { name: "Loretta MacCarter", language: "Kuanyama", company: "Eayo", departure: "Research and Development" },
  { name: "Charmian Panton", language: "Kazakh", company: "Midel", departure: "Sales" },
  { name: "Lee Chmarny", language: "Bengali", company: "Aimbu", departure: "Human Resources" },
  { name: "Loralyn Hawkeridge", language: "Yoruba", company: "Leenti", departure: "Marketing" },
  { name: "Nananne Labuschagne", language: "Inupiaq", company: "Youopia", departure: "Engineering" },
  { name: "Jasper Bishop", language: "Portuguese", company: "Jabberbean", departure: "Accounting" },
  { name: "Gilly Rupp", language: "Catalan", company: "Fadeo", departure: "Accounting" },
  { name: "Feliza Popov", language: "Arabic", company: "Yabox", departure: "Engineering" },
  { name: "Marena Barttrum", language: "Norwegian Nynorsk", company: "Yodo", departure: "Services" },
  { name: "Hagen Ingerith", language: "Romansh", company: "Feedspan", departure: "Marketing" },
  { name: "Pearla Yearn", language: "Macedonian", company: "Devpoint", departure: "Training" },
  { name: "Remy Barabisch", language: "Romanian", company: "Shufflebeat", departure: "Training" },
  { name: "Lana Leneve", language: "Ndebele, South", company: "Kazio", departure: "Services" },
  { name: "Colman Metcalfe", language: "Inupiaq", company: "Kanoodle", departure: "Accounting" },
  { name: "Darill Biermatowicz", language: "Chinese", company: "Centimia", departure: "Sales" },
  { name: "Trenna Bunney", language: "Zhuang", company: "Pixope", departure: "Business Development" },
  { name: "Cherie Piken", language: "Fijian", company: "Tagchat", departure: "Sales" },
  { name: "Julie Douglass", language: "Sanskrit", company: "Jaloo", departure: "Product Management" },
  { name: "Carling Silber", language: "Esperanto", company: "Tagchat", departure: "Business Development" },
  { name: "Vina Tubbles", language: "Kikuyu", company: "Browsebug", departure: "Human Resources" },
  { name: "Bernete O'Sherrin", language: "Kurdish", company: "Photobug", departure: "Engineering" },
  { name: "Juline Kuhnwald", language: "Kazakh", company: "Plajo", departure: "Accounting" },
  { name: "Stesha Witham", language: "Gujarati", company: "Topicware", departure: "Marketing" },
  { name: "Emily Kryska", language: "Xhosa", company: "Fivebridge", departure: "Support" },
  { name: "Barb Collinwood", language: "Yoruba", company: "Yamia", departure: "Product Management" },
  { name: "Margaretha Slott", language: "Bislama", company: "Kazio", departure: "Product Management" },
  { name: "Kayley Evill", language: "Swahili", company: "Jetwire", departure: "Product Management" },
  { name: "Bartholemy Stockford", language: "Finnish", company: "Podcat", departure: "Accounting" },
  { name: "Rosa Enstone", language: "Japanese", company: "Tagcat", departure: "Accounting" },
  { name: "Leanna Coppenhall", language: "Chuvash", company: "Zooveo", departure: "Accounting" },
  { name: "Bili Bellam", language: "Fijian", company: "Yodel", departure: "Product Management" },
  { name: "Kizzee Silversmidt", language: "English", company: "Jaxbean", departure: "Human Resources" },
  { name: "Millicent Wratten", language: "Kazakh", company: "Livetube", departure: "Support" },
  { name: "Lolita Huban", language: "Bokmål, Norwegian", company: "Myworks", departure: "Accounting" },
  { name: "Hanna Cawthron", language: "Kongo", company: "Kwimbee", departure: "Services" },
  { name: "Raymond Gethins", language: "Breton", company: "Thoughtblab", departure: "Accounting" },
  { name: "Alfie Lidyard", language: "Bambara", company: "Dabjam", departure: "Engineering" },
  { name: "Mackenzie McGonagle", language: "Limburgan", company: "Trunyx", departure: "Legal" },
  { name: "Leia Bercevelo", language: "Irish", company: "Babbleblab", departure: "Business Development" },
  { name: "Cinderella Songest", language: "Manx", company: "Talane", departure: "Human Resources" },
  { name: "Zuzana Burkert", language: "Ukrainian", company: "Centidel", departure: "Services" },
  { name: "Jessa Rookwell", language: "Arabic", company: "Yodo", departure: "Training" },
  { name: "Hildegarde Mallabund", language: "Interlingua (International Auxiliary Language Association)", company: "Youspan", departure: "Business Development" },
  { name: "Ronda Stoad", language: "Cree", company: "Trudeo", departure: "Sales" },
  { name: "Kakalina Sinnocke", language: "Hebrew", company: "Trudeo", departure: "Support" },
  { name: "Jesus Jikovsky", language: "German", company: "Eare", departure: "Research and Development" },
  { name: "Emilie Solway", language: "Xhosa", company: "Skiba", departure: "Legal" },
  { name: "Lorinda Eul", language: "Aymara", company: "Jayo", departure: "Research and Development" },
  { name: "Niels Jellard", language: "Guarani", company: "Twinder", departure: "Training" },
  { name: "Shae Gadsby", language: "Tamil", company: "Jazzy", departure: "Training" },
  { name: "Hiram Crusham", language: "Sanskrit", company: "Zazio", departure: "Training" },
  { name: "Tonia Minillo", language: "Belarusian", company: "Bubbletube", departure: "Support" },
  { name: "Chuck Elsby", language: "Vietnamese", company: "Wikido", departure: "Research and Development" },
  { name: "Huntington May", language: "Church Slavic", company: "Feedmix", departure: "Sales" },
  { name: "Randi Pillans", language: "Dutch", company: "Flashpoint", departure: "Business Development" },
  { name: "Tiphanie McDavitt", language: "Marshallese", company: "Cogibox", departure: "Product Management" },
  { name: "Blondelle Bramham", language: "Inuktitut", company: "Thoughtworks", departure: "Human Resources" },
  { name: "Madelyn Riccelli", language: "Wolof", company: "Edgewire", departure: "Training" },
  { name: "Howard Barbour", language: "English", company: "Zoonoodle", departure: "Product Management" },
  { name: "Corny Smout", language: "Luxembourgish", company: "Photolist", departure: "Sales" },
  { name: "Shalna Shill", language: "Uzbek", company: "Gabvine", departure: "Business Development" },
  { name: "Gayla Starkings", language: "Chinese", company: "Livepath", departure: "Business Development" },
  { name: "Lauryn Elnaugh", language: "Corsican", company: "Mydo", departure: "Support" },
  { name: "Annabell Cartman", language: "Haitian", company: "Pixonyx", departure: "Marketing" },
  { name: "Roxanna Budgey", language: "Avaric", company: "Feednation", departure: "Support" },
  { name: "Suzy Fright", language: "Zhuang", company: "Livepath", departure: "Business Development" },
  { name: "Garrett Mill", language: "Malayalam", company: "Wikizz", departure: "Human Resources" },
  { name: "Jean McCafferky", language: "Hebrew", company: "Browseblab", departure: "Legal" },
  { name: "Arty Sayer", language: "Swedish", company: "Quimm", departure: "Marketing" },
  { name: "Aprilette Challenger", language: "Welsh", company: "Zooxo", departure: "Support" },
  { name: "Godfree Herrema", language: "Rundi", company: "Skinix", departure: "Business Development" },
  { name: "Kin Ledstone", language: "Kannada", company: "Latz", departure: "Training" },
  { name: "Cecilius Adney", language: "Serbian", company: "Tagcat", departure: "Training" },
  { name: "Margie Bartolomeo", language: "Sichuan Yi", company: "Topicshots", departure: "Training" },
  { name: "Jillian Father", language: "Marshallese", company: "Shuffletag", departure: "Engineering" },
  { name: "Ev Gussin", language: "Bislama", company: "Meejo", departure: "Legal" },
  { name: "Charis Linnane", language: "Interlingue", company: "Ozu", departure: "Engineering" },
  { name: "Consalve McKie", language: "Tonga (Tonga Islands)", company: "Topicware", departure: "Legal" },
  { name: "Nancy Maffione", language: "Oriya", company: "Snaptags", departure: "Marketing" },
  { name: "Shaine Dimont", language: "Welsh", company: "Dabshots", departure: "Sales" },
  { name: "Alic Fearey", language: "Irish", company: "Flipopia", departure: "Services" },
  { name: "Kurtis Steely", language: "Cree", company: "Trunyx", departure: "Business Development" },
  { name: "Deanne Hedgecock", language: "Hebrew", company: "Lazz", departure: "Sales" },
  { name: "Hakeem Layzell", language: "Lithuanian", company: "Fliptune", departure: "Marketing" },
  { name: "Dion Champney", language: "Xhosa", company: "Bluezoom", departure: "Services" },
  { name: "Rachael Jouhandeau", language: "Uighur", company: "Rhynoodle", departure: "Support" },
  { name: "Mathilda Dadds", language: "Mongolian", company: "Blogpad", departure: "Business Development" },
  { name: "Brandtr Baldocci", language: "Albanian", company: "Tambee", departure: "Sales" },
  { name: "Galvan Vial", language: "Afrikaans", company: "Gevee", departure: "Engineering" },
  { name: "Ulberto Duerdin", language: "Komi", company: "Talane", departure: "Accounting" },
  { name: "Melli Gyrgorwicx", language: "Church Slavic", company: "Yabox", departure: "Research and Development" },
  { name: "Alfie Hutchinson", language: "Tigrinya", company: "Fivebridge", departure: "Training" },
  { name: "Lynda Garoghan", language: "Swati", company: "Twitterbeat", departure: "Business Development" },
  { name: "Scott Perree", language: "Hindi", company: "Twitterbridge", departure: "Accounting" },
  { name: "Cleo Brundell", language: "Kuanyama", company: "Katz", departure: "Engineering" },
  { name: "Imojean Grzesiewicz", language: "Quechua", company: "Eire", departure: "Business Development" },
  { name: "Barby Whorf", language: "Sichuan Yi", company: "Tagtune", departure: "Marketing" },
  { name: "Stuart Stiffell", language: "Tatar", company: "Brainverse", departure: "Training" },
  { name: "Thelma Heliet", language: "Yiddish", company: "Twitterbridge", departure: "Training" },
  { name: "Maren Hearnes", language: "Japanese", company: "Tekfly", departure: "Support" },
  { name: "Englebert Collard", language: "Icelandic", company: "Voonyx", departure: "Product Management" },
  { name: "Onida Belliard", language: "Chichewa", company: "Kayveo", departure: "Accounting" },
  { name: "Gabriellia Goundrill", language: "Kongo", company: "Centizu", departure: "Sales" },
  { name: "Almire Pointer", language: "Sardinian", company: "Yamia", departure: "Engineering" },
  { name: "Gardie Capstack", language: "Tamil", company: "Mybuzz", departure: "Research and Development" },
  { name: "Elie Skentelbury", language: "Tibetan", company: "Skipfire", departure: "Product Management" },
  { name: "Sherlocke Corpe", language: "Portuguese", company: "Skilith", departure: "Support" },
  { name: "Aldus Lucas", language: "Nauru", company: "Skinte", departure: "Engineering" },
  { name: "Georges Stot", language: "Polish", company: "Dynabox", departure: "Services" },
  { name: "Robinetta Risebarer", language: "Norwegian Nynorsk", company: "Feedbug", departure: "Human Resources" },
  { name: "Markus Scarff", language: "Turkish", company: "Nlounge", departure: "Sales" },
  { name: "Jan Mocher", language: "Ossetian", company: "Digitube", departure: "Sales" },
  { name: "Lauraine Mintrim", language: "Guarani", company: "Gigaclub", departure: "Legal" },
  { name: "Sonny McGinty", language: "Sundanese", company: "Mita", departure: "Product Management" },
  { name: "James Escolme", language: "Czech", company: "Tambee", departure: "Training" },
  { name: "Maryrose Scogin", language: "Maltese", company: "Centidel", departure: "Human Resources" },
  { name: "Arlin Mickelwright", language: "Swahili", company: "Brightdog", departure: "Accounting" },
  { name: "Lauralee Stainbridge", language: "Guarani", company: "Devbug", departure: "Support" },
  { name: "Rayner D'Ambrogi", language: "Chuvash", company: "Cogidoo", departure: "Training" },
  { name: "Rudiger Frend", language: "Guarani", company: "Pixoboo", departure: "Research and Development" },
  { name: "Inger Geall", language: "Quechua", company: "Demivee", departure: "Support" },
  { name: "Tina Cokayne", language: "Indonesian", company: "Pixoboo", departure: "Marketing" },
  { name: "Bennett Dunbleton", language: "Northern Sami", company: "Photolist", departure: "Human Resources" },
  { name: "Christy Drysdall", language: "Northern Sami", company: "Vinder", departure: "Accounting" },
  { name: "Joanie Davidovics", language: "Spanish", company: "Babbleset", departure: "Research and Development" },
  { name: "Giselbert Gounet", language: "Fijian", company: "Voonix", departure: "Marketing" },
  { name: "Marylee Nuzzi", language: "Sindhi", company: "Jaxbean", departure: "Training" },
  { name: "Barnard Petrina", language: "Sinhala", company: "Lazz", departure: "Research and Development" },
  { name: "Haley Shapter", language: "Bokmål, Norwegian", company: "Wikido", departure: "Training" },
  { name: "Doloritas Lukianov", language: "Sindhi", company: "Jabbersphere", departure: "Sales" },
  { name: "Link Shrimpton", language: "Greek, Modern (1453-)", company: "Wikido", departure: "Sales" },
  { name: "Vida Freezor", language: "Interlingua (International Auxiliary Language Association)", company: "Lazz", departure: "Business Development" },
  { name: "Otes Grogono", language: "Pali", company: "Thoughtbeat", departure: "Support" },
  { name: "Dulcia Sicely", language: "Inupiaq", company: "Flashpoint", departure: "Legal" },
  { name: "Jerrine Da Costa", language: "Ewe", company: "Gabtype", departure: "Legal" },
  { name: "Wynn Snozzwell", language: "Pali", company: "Wikizz", departure: "Sales" },
  { name: "Rickert Tryhorn", language: "Norwegian", company: "Oyoba", departure: "Services" },
  { name: "Marlane Beak", language: "Tahitian", company: "Quire", departure: "Research and Development" },
  { name: "Gar Peppin", language: "Tibetan", company: "Topiczoom", departure: "Legal" },
  { name: "Corissa Filyushkin", language: "Kinyarwanda", company: "Gabcube", departure: "Marketing" },
  { name: "Boniface Bunning", language: "Japanese", company: "Wordpedia", departure: "Engineering" },
  { name: "Pauline Marcum", language: "Norwegian Nynorsk", company: "Photojam", departure: "Human Resources" },
  { name: "Aubree Klesel", language: "Sindhi", company: "Aimbu", departure: "Sales" },
  { name: "Garwin Peploe", language: "Zhuang", company: "Dynabox", departure: "Human Resources" },
  { name: "Darla Kirtlan", language: "Guarani", company: "Shufflebeat", departure: "Marketing" },
  { name: "Joshia Kerrich", language: "Bokmål, Norwegian", company: "Photolist", departure: "Sales" },
  { name: "Rusty Scutts", language: "Georgian", company: "Photojam", departure: "Business Development" },
  { name: "Harriot Almey", language: "Maori", company: "Pixope", departure: "Accounting" },
  { name: "Shelby Mongenot", language: "Corsican", company: "Twitterworks", departure: "Accounting" },
  { name: "Sile Eayrs", language: "Uzbek", company: "Jatri", departure: "Business Development" },
  { name: "Nicki Coffelt", language: "Ido", company: "Edgeblab", departure: "Sales" },
  { name: "Hube Berick", language: "Sundanese", company: "Fliptune", departure: "Legal" },
  { name: "Florella Alday", language: "Pali", company: "Realpoint", departure: "Research and Development" },
  { name: "Rafe Atton", language: "Sindhi", company: "Zoomzone", departure: "Sales" },
  { name: "Wally Dewbury", language: "Galician", company: "Shuffledrive", departure: "Services" },
  { name: "Antonio Halle", language: "Irish", company: "Zoomdog", departure: "Services" },
  { name: "Levi Tomaszkiewicz", language: "Polish", company: "Pixope", departure: "Services" },
  { name: "Riane Synan", language: "Tibetan", company: "Gigaclub", departure: "Training" },
  { name: "Carin Hellis", language: "Georgian", company: "Yambee", departure: "Research and Development" },
  { name: "Carlita Halloran", language: "Malay", company: "Muxo", departure: "Business Development" },
  { name: "Gayle Bellany", language: "Hiri Motu", company: "Plambee", departure: "Sales" },
  { name: "Laurice Flute", language: "Xhosa", company: "Twimbo", departure: "Legal" },
  { name: "Frederik Rodolf", language: "Sanskrit", company: "Meeveo", departure: "Services" },
  { name: "Inna Chaperling", language: "Albanian", company: "Trudeo", departure: "Product Management" },
  { name: "Evaleen Cavet", language: "Latin", company: "Vinder", departure: "Business Development" },
  { name: "Jesselyn Lamminam", language: "Marshallese", company: "Mynte", departure: "Human Resources" },
  { name: "Odelinda Legh", language: "Wolof", company: "Vinder", departure: "Product Management" },
  { name: "Nigel Wimbury", language: "Persian", company: "Feedfish", departure: "Services" },
  { name: "Conant Thwaites", language: "Shona", company: "Abatz", departure: "Training" },
  { name: "Ursola Espley", language: "Quechua", company: "Thoughtblab", departure: "Services" },
  { name: "Barbette Faye", language: "Malagasy", company: "Bubblebox", departure: "Services" },
  { name: "Roderick Chesher", language: "Maori", company: "Zava", departure: "Product Management" },
  { name: "Yevette Racher", language: "Korean", company: "Dazzlesphere", departure: "Services" },
  { name: "Ulrica Stronough", language: "Ido", company: "Wikizz", departure: "Engineering" },
  { name: "Sullivan Corcut", language: "Tibetan", company: "Livetube", departure: "Training" },
  { name: "Peyter Fencott", language: "Bambara", company: "Skinix", departure: "Sales" },
  { name: "Koressa Iczokvitz", language: "Indonesian", company: "Jaxnation", departure: "Accounting" },
  { name: "Garner Cashin", language: "Inuktitut", company: "Blogtags", departure: "Research and Development" },
  { name: "Iolanthe Chasmar", language: "Chinese", company: "Twimm", departure: "Services" },
  { name: "Boigie Ghelardoni", language: "Chuvash", company: "Demimbu", departure: "Marketing" },
  { name: "Sibeal Mottinelli", language: "Hiri Motu", company: "Realmix", departure: "Business Development" },
  { name: "Hill Tomadoni", language: "Esperanto", company: "Jabbersphere", departure: "Legal" },
  { name: "Alejoa Konneke", language: "Sanskrit", company: "Quimba", departure: "Business Development" },
  { name: "Fremont Posner", language: "Uzbek", company: "Muxo", departure: "Engineering" },
  { name: "Meaghan Pinxton", language: "Interlingue", company: "Blogpad", departure: "Marketing" },
  { name: "Misty Hindenberger", language: "Aragonese", company: "Agimba", departure: "Human Resources" },
  { name: "Matelda Le Franc", language: "Ukrainian", company: "Youspan", departure: "Accounting" },
  { name: "Ethel Duplan", language: "Limburgan", company: "Realcube", departure: "Marketing" },
  { name: "Gerry Aiston", language: "Basque", company: "Quinu", departure: "Product Management" },
  { name: "Kennan Marking", language: "Venda", company: "Divanoodle", departure: "Services" },
  { name: "Wald Sarver", language: "Hindi", company: "Realbuzz", departure: "Product Management" },
  { name: "Sharity Tuerena", language: "Assamese", company: "Latz", departure: "Support" },
  { name: "Cathee Gittis", language: "Lithuanian", company: "Tagopia", departure: "Marketing" },
  { name: "Davidson McGrady", language: "Pali", company: "Edgepulse", departure: "Human Resources" },
  { name: "Bryn Netti", language: "Japanese", company: "Gigazoom", departure: "Training" },
  { name: "Cindee Kiebes", language: "Romanian", company: "Rhycero", departure: "Accounting" },
  { name: "Dougy Orry", language: "Icelandic", company: "Agivu", departure: "Accounting" },
  { name: "Fredric Oakhill", language: "Chamorro", company: "Wordify", departure: "Engineering" },
  { name: "Amalie Macrow", language: "Estonian", company: "Divavu", departure: "Engineering" },
  { name: "Tildie Laffoley-Lane", language: "Oriya", company: "Kwimbee", departure: "Training" },
  { name: "Joshuah Barbery", language: "Welsh", company: "Meetz", departure: "Support" },
  { name: "Evelyn Danieli", language: "Indonesian", company: "Kwinu", departure: "Legal" },
  { name: "Sapphira Baguley", language: "Welsh", company: "Livetube", departure: "Business Development" },
  { name: "Lavinia Dowley", language: "Zulu", company: "Skyble", departure: "Training" },
  { name: "Annissa Scartifield", language: "Interlingua (International Auxiliary Language Association)", company: "Photobug", departure: "Accounting" },
  { name: "Heinrik Stych", language: "Tibetan", company: "Wordware", departure: "Engineering" },
  { name: "Darrin Tatton", language: "Belarusian", company: "Vinder", departure: "Legal" },
  { name: "Gladys Turbard", language: "Kuanyama", company: "InnoZ", departure: "Research and Development" },
  { name: "Orella Henryson", language: "Korean", company: "Browsedrive", departure: "Business Development" },
  { name: "Cherri Fliege", language: "Abkhazian", company: "Photobug", departure: "Human Resources" },
  { name: "Batholomew Lefridge", language: "Zhuang", company: "Roodel", departure: "Human Resources" },
  { name: "Brigitte Cowthard", language: "Tonga (Tonga Islands)", company: "Thoughtbeat", departure: "Engineering" },
  { name: "Tulley Quick", language: "Chechen", company: "Zoozzy", departure: "Support" },
  { name: "Xenia Alonso", language: "Maltese", company: "Skilith", departure: "Business Development" },
  { name: "Niels Fitter", language: "Sindhi", company: "Mydeo", departure: "Legal" },
  { name: "Ajay Paylor", language: "Breton", company: "Browsecat", departure: "Training" },
  { name: "Serena Rankine", language: "Marshallese", company: "Roombo", departure: "Product Management" },
  { name: "Maxy Shergold", language: "Nepali", company: "Zoombox", departure: "Business Development" },
  { name: "Fanny Trotter", language: "Pushto", company: "Roomm", departure: "Product Management" },
  { name: "Ellissa Claybourn", language: "Estonian", company: "Browseblab", departure: "Human Resources" },
  { name: "Guendolen Tollady", language: "Azerbaijani", company: "Zoomzone", departure: "Product Management" },
  { name: "Zsa zsa Sherwen", language: "Interlingue", company: "Jaxspan", departure: "Services" },
  { name: "Christine Tingly", language: "Inuktitut", company: "Abatz", departure: "Business Development" },
  { name: "Belita Hearley", language: "Divehi", company: "Centimia", departure: "Marketing" },
  { name: "Leland Husthwaite", language: "Western Frisian", company: "Fatz", departure: "Legal" },
  { name: "Roselia Treacher", language: "Rundi", company: "Voolia", departure: "Accounting" },
  { name: "Nev Bertolin", language: "Ossetian", company: "Demivee", departure: "Training" },
  { name: "Florance Basset", language: "Galician", company: "Ailane", departure: "Support" },
  { name: "Orv Bever", language: "Venda", company: "Flashset", departure: "Services" },
  { name: "Belita Artharg", language: "Limburgan", company: "Fivechat", departure: "Sales" },
  { name: "Pamella Leitche", language: "Shona", company: "Skiba", departure: "Product Management" },
  { name: "Christen Prozillo", language: "Marathi", company: "Photojam", departure: "Business Development" },
  { name: "Kerianne Sheerman", language: "Faroese", company: "Tanoodle", departure: "Human Resources" },
  { name: "Jerald Rooke", language: "Tonga (Tonga Islands)", company: "Photobug", departure: "Product Management" },
  { name: "Hildagard Carneck", language: "Ndebele, North", company: "Mudo", departure: "Product Management" },
  { name: "Dido Scrymgeour", language: "Tonga (Tonga Islands)", company: "JumpXS", departure: "Business Development" },
  { name: "Pepe Goddman", language: "Inupiaq", company: "Livetube", departure: "Marketing" },
  { name: "Ginger Mardling", language: "Javanese", company: "Kazio", departure: "Human Resources" },
  { name: "Dallon Gavahan", language: "Bislama", company: "Kare", departure: "Engineering" },
  { name: "Wileen Titheridge", language: "Kurdish", company: "Divape", departure: "Sales" },
  { name: "Kristopher Camocke", language: "Ndebele, South", company: "Zoomzone", departure: "Engineering" },
  { name: "Margalit Glasspoole", language: "Norwegian", company: "Oozz", departure: "Support" },
  { name: "Fanchon Lemary", language: "Shona", company: "Vimbo", departure: "Training" },
  { name: "Jennica Zahor", language: "Bambara", company: "Yodel", departure: "Legal" },
  { name: "Cliff Willars", language: "Inuktitut", company: "BlogXS", departure: "Services" },
  { name: "Ailee Delacoste", language: "Oriya", company: "Mynte", departure: "Research and Development" },
  { name: "Jerrome Ingre", language: "Nauru", company: "Fivebridge", departure: "Marketing" },
  { name: "Carly Bladge", language: "Haitian", company: "Skaboo", departure: "Marketing" },
  { name: "Beulah Coyne", language: "Bislama", company: "Kare", departure: "Human Resources" },
];

module.exports = { data };
